### ISSUE TITLE
Hurawatch | hurawatch.cc

### ISSUE THREAD

**Issue by soulrunsu** [PreMiD/Presences#8657] opened 2024-08-14 13:14 UTC
### Website name

Hurawatch

### Website URL

https://hurawatch.cc/

### Website logo

https://img.hurawatch.cc/xxrz/400x400/100/88/52/88526f5e66ecc3b78ee9a1744d4c8457/88526f5e66ecc3b78ee9a1744d4c8457.png

### Prerequisites

- [ ] It is a paid service
- [ ] It is region restricted

### Description

its a movie website

**Comment by theusaf** [comment] 2024-08-17 17:45
Duplicate of #5253

**Closed by theusaf** 2024-08-17 17:45 UTC
Labels: service request
