### ISSUE TITLE
Ryuten.io | Ryuten.io

### ISSUE THREAD

**Issue by SeMiD** [PreMiD/Presences#5238] opened 2022-01-03 02:58 UTC
### Discussed in https://github.com/PreMiD/Presences/discussions/5176

<div type='discussions-op-text'>

<sup>Originally posted by **SirDread** December 28, 2021</sup>
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's the name of the service?**
Ryuten.io - https://ryuten.io/ 

**What should the Presence display?** 
Server Region, Game Mode, Mass Amount Player Has, Time Alive, Tag player is in, If the player hasn't spawned in yet, it can say on the presence the region the player has selected and underneath it, it can show "Spectating"
Example:  
NA | War Training 
[tag]Player123 : 34.7k : Time Alive: 5:00 
the time alive should reset everytime the player dies and spawns back in 

Example for spectating:
NA | War Training 
Spectating 

**If possible, please provide a logo for the service (512x512 minimum)** 

![131683805_101393248540144_1957058793901587813_n_512x512](https://user-images.githubusercontent.com/92899130/147599225-1e45bd1b-ac38-42a3-aef3-160c6175f821.jpg)

</div>

**Comment by joerkig** [comment] 2022-01-09 04:10
Duplicate of #5390

**Closed** 2022-01-09 08:34 UTC
Labels: Service Request
