### ISSUE TITLE
YouTube Music | music.youtube.com | v3.0.22 - Rich presence does not appear in discord

### ISSUE THREAD

**Issue by Jayden130** [PreMiD/Presences#8941] opened 2024-12-08 18:04 UTC
### Steps to Reproduce

1. Open YouTube music (desktop chrome app or chrome)
2. Start a song

### Expected Behavior

It shows up as rich presence

### Actual Behavior

It doesn't show a rich presence

### Page URL

https://music.youtube.com/watch?v=Hd19KBE0hn0

### Operating System

Windows 10

### Browser and Version

Google Chrome Version 131.0.6778.109 (Official Build) (64-bit)

### Additional Comments

YouTube *does* work, YouTube music does not

**Comment by moyaimoment** [comment] 2024-12-08 20:42
> 1. desktop chrome app

Doesn't work in the Desktop Chrome App only website.

Are your Activities on Discord turned on?
Do other presences show up?

**Comment by Jayden130** [comment] 2024-12-09 15:26
Yep, I tested in both the website and app, other presences *do* show up, and activities are enabled in my discord.

**Comment by theusaf** [comment] 2024-12-09 16:42
Duplicate of #7094

**Closed by theusaf** 2024-12-09 16:42 UTC
Labels: bug, needs repro
