### ISSUE TITLE
Last.fm

### ISSUE THREAD

**Issue by fl34b4g** [PreMiD/Presences#1770] opened 2020-06-16 19:05 UTC
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 

**What's the name of the service?** 
www.last.fm | Last.fm
**What should the Presence display?** 
What music you're playing or what page you're browsing.
**If possible, please provide a logo for the service (512x512 minimum)** 
![lastfm_avatar_twitter 66cd2c48ce03](https://user-images.githubusercontent.com/52077646/84817363-187f0200-b015-11ea-9540-35ac8c38a734.png)

**Comment by Hans5958** [comment] 2020-06-17 12:40
Duplicate of #1020, in progress on #1418.

**Closed** 2020-06-17 20:05 UTC
