### ISSUE TITLE
moviesjoy | moviesjoy.to

### ISSUE THREAD

**Issue by he4rtana** [PreMiD/Presences#7276] opened 2023-04-06 03:47 UTC
### Website name

moviesjoy

### Website URL

https://moviesjoy.to/

### Website logo

https://cdn.discordapp.com/attachments/735024084349485086/1093381229656690738/image.png

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

u guys should add this website fr

**Comment by sweezyio** [comment] 2023-04-07 23:58
Could you please change the title of this issue to follow the proper naming conventions?

The title should be in the form of `Service Name | Service URL`.

**Comment by DarkVillager** [comment] 2023-04-08 16:23
Duplicate of #5312

**Comment by DarkVillager** [comment] 2023-04-08 18:49
> Duplicate of #5312

@Bas950

**Closed** 2023-04-08 18:53 UTC
Labels: service request

**Comment by he4rtana** [comment] 2023-04-12 22:07
r yall gonna add it in?

**Comment by sweezyio** [comment] 2023-04-15 06:55
@he4rtana First, this particular site was requested in #5312 over a year ago, you should have checked for it before making your issue. Second, the addition of presences is done on a volunteer basis usually by the people who want the presence to be a thing in the first place. And seeing as how this site is just another illegal streaming site, I don't really think there is much demand for it to be added in general.
