### ISSUE TITLE
HBO GO - JUST DISPLAYING "Browsing..." INSTEAD OF SHOWING TITLES

### ISSUE THREAD

**Issue by Kazuhira17** [PreMiD/Presences#7230] opened 2023-01-16 14:25 UTC
**Describe the bug**
It doesn't display the shows I'm watching. It only shows that I'm browsing even though I'm already watching something.

**To Reproduce**
1. Open both Premid and Discord
2. Open HBO GO on Browser
3. Watch anything

**Expected behavior**
I just need it to display the shows I'm currently watching.

**Screenshots**
![Screenshot (606)](https://user-images.githubusercontent.com/107014929/212700807-67eb2be0-cffe-4dc2-857d-2174f90954f8.png)

**Desktop (please complete the following information):**
 - Win 10 64 Bit- OS: [e.g. iOS]
 - Chrome

**Additional context**

**Comment by sweezyio** [comment] 2023-04-08 00:11
Duplicate of #7125

**Closed** 2023-05-21 17:17 UTC
