### ISSUE TITLE
Animeflash | https://animeflash.xyz/

### ISSUE THREAD

**Issue by GuestAsUsual** [PreMiD/Presences#5550] opened 2022-01-09 08:05 UTC
### Website name

Animeflash

### Website URL

https://animeflash.xyz/

### Website logo

https://imgur.com/wPwprxF

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

I'd like to see the same stuff displayed as crunchyroll (what im watching, how much time is left, and two buttons of watch series and episode)
![image](https://user-images.githubusercontent.com/97380507/148674347-522e6439-0272-4b7e-992a-d59cf9b96f68.png)

**Comment by Slowlife01** [comment] 2022-01-09 08:35
Duplicate of #5261

**Closed by Slowlife01** 2022-01-09 08:35 UTC
Labels: Service Request
