### ISSUE TITLE
Yugen Anime’s Presence’s Needs an Update

### ISSUE THREAD

**Issue by roufflez** [PreMiD/Presences#7507] opened 2023-07-21 20:09 UTC
### Presence name

Yugen Anime

### Description

Yugen anime has changed its URL, it was originally yugen.to but now it’s yugenanime.tv, since the URL has changed, the presence no longer works. May someone please update the presence to match the new URL?

**Comment by theusaf** [comment] 2023-07-21 21:15
Duplicate of #7391

**Closed by theusaf** 2023-07-21 21:15 UTC
Labels: feature request
