### ISSUE TITLE
Braflix | www.braflix.is

### ISSUE THREAD

**Issue by brxndonnn** [PreMiD/Presences#8833] opened 2024-10-23 14:28 UTC
### Website name

Braflix

### Website URL

https://www.braflix.is/

### Website logo

https://www.braflix.is/logo.png

### Prerequisites

- [ ] It is a paid service
- [ ] It is region restricted

### Description

I’d like to request adding a Braflix presence to Premid.

This feature should update in real time to reflect what users are watching on Braflix.

**Comment by tag27** [comment] 2024-10-24 22:41
Duplicate of #8644

**Closed** 2024-10-25 20:15 UTC
Labels: service request
