### ISSUE TITLE
HBO Max Stuck at "Browsing..."

### ISSUE THREAD

**Issue by LieutenantSugar** [PreMiD/Presences#8235] opened 2024-03-31 22:15 UTC
### Steps to Reproduce

1) Open both Discord and Premid app
2) Go to hbomax.com or max.com
3) Pick a show or movie

### Expected Behavior

Display the show/movie I'm watching

### Actual Behavior

Just shows "Browsing..."

### Page URL

https://play.max.com/

### Screenshots

![HBO 0](https://github.com/PreMiD/Presences/assets/59771363/d994d315-4c2b-4e0f-9ea7-42dac9afaa1e)
![HBO 1](https://github.com/PreMiD/Presences/assets/59771363/da742a9b-53df-462a-8a63-25a7f4e24e0e)

### Operating System

Windows 11

### Browser and Version

Latest versions of Google Chrome and Mozilla Firefox

### Additional Comments

This issue is identical to #7125

**Comment by tag27** [comment] 2024-03-31 22:27
Duplicate of #7371

**Closed** 2024-03-31 22:43 UTC
Labels: bug, needs repro
