### ISSUE TITLE
Nutaku (NSFW) Premid it does not work

### ISSUE THREAD

**Issue by DiegoYisus** [PreMiD/Presences#6450] opened 2022-07-14 15:51 UTC
### Steps to Reproduce

https://www.nutaku.net/home/
Check out the premid.

### Expected Behavior

that the presence of nutaku will function normally as the other premid 

### Actual Behavior

Nutaku premid site is not working 

### Page URL

https://www.nutaku.net/home/

### Screenshots

![Captura de pantalla 2022-07-14 084421](https://user-images.githubusercontent.com/107974177/179024116-014a5ec2-05d7-46b6-bea6-0eb59d77220a.jpg)

### Operating System

windows 10 home

### Browser and Version

brave, google

**Comment by RisingSunLight42** [comment] 2022-07-14 22:53
![image](https://user-images.githubusercontent.com/85577959/179103112-c2d980e8-6cff-4b3d-a17d-72c67ba51286.png)
I can confirm there's a bug with the presence.

**Comment by RisingSunLight42** [comment] 2022-07-14 23:43
I can't repro it, looks like in test the error isn't showing even if the presence is not working too, but here's the complete error :
![image](https://user-images.githubusercontent.com/85577959/179119128-651c6e04-f455-4c80-98ca-28ecec5ca9ca.png)

**Comment by RisingSunLight42** [comment] 2022-08-19 14:10
I've checked again. Looks like it's an error on PreMiD's side, not the presence's side, since the error doesn't appear in dev.

**Comment by x1mv** [comment] 2022-08-27 19:11
bro thank god go get a life

**Comment by tag27** [comment] 2024-04-19 11:41
It would be good to close this Issue, since we no longer accept NSFW presences.

**Closed** 2024-04-19 17:09 UTC
Labels: bug, needs repro
