### ISSUE TITLE
Add Facebook Reels support

### ISSUE THREAD

**Issue by PhilMinecraft** [PreMiD/Presences#6602] opened 2022-08-05 13:46 UTC
### Presence name

Facebook

### Description

Add Facebook Reels support that's same as on TikTok

### Alternatives

TikTok, YouTube Shorts, Instagram Reels

### Additional context

When viewing a reel, if a reel I'm watching is specific, it should display "Reels - Viewing PhilMinecraft's reel: it's #reels time" and if I next the reel, it should only display "Reels - Watching a reel"
![fb reels 1](https://user-images.githubusercontent.com/67897800/183090214-91633a5f-426e-4cae-aedc-b44d6f6be412.png)
![fb reels 2](https://user-images.githubusercontent.com/67897800/183090223-91ead1f2-0e28-49f8-901c-e6a254d1294b.png)

**Comment by RisingSunLight42** [comment] 2022-08-05 13:51
Duplicate of #6218

**Comment by callumok2004** [comment] 2022-08-06 03:14
Duplicate of #6218, either close the existing issue or close this one and add the extra screenshots and information to the existing one!

**Closed** 2022-08-09 14:32 UTC
Labels: feature request
