### ISSUE TITLE
Viz | www.viz.com

### ISSUE THREAD

**Issue by Gabe2668** [PreMiD/Presences#8455] opened 2024-06-04 00:50 UTC
### Website name

Viz

### Website URL

https://www.viz.com/

### Website logo

https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.facebook.com%2FOfficialVIZMedia%2F&psig=AOvVaw2cMcQNeRe3YVDQKGScm4RX&ust=1717548540546000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCNC3lobdwIYDFQAAAAAdAAAAABAE

### Prerequisites

- [ ] It is a paid service
- [ ] It is region restricted

### Description

Viz manga and Shonen jump pressence.

i tried to make myself by couldn't lol

If it could just say the series and the current chapter that would be fire

**Comment by tag27** [comment] 2024-06-04 23:49
Duplicate of #5468

**Closed** 2024-06-05 02:46 UTC
Labels: service request
