### ISSUE TITLE
Osn new presence

### ISSUE THREAD

**Issue by Almukhtar1** [PreMiD/Presences#7622] opened 2023-09-08 06:12 UTC
### Website name

Osn+

### Website URL

https://osnplus.com/

### Website logo

https://www.osn.com/osn/media/OSNMedia/osn-tv-home/apps-icon/osnplus-app.svg

### Prerequisites

- [X] It is a paid service
- [ ] It displays NSFW content
- [X] It is region restricted

### Description

same as netflix / Hbo

**Comment by theusaf** [comment] 2023-09-08 06:26
Duplicate of #6827

**Closed by theusaf** 2023-09-08 06:26 UTC
Labels: service request
