### ISSUE TITLE
Soap2Day | soap2day.to

### ISSUE THREAD

**Issue by aidanhub** [PreMiD/Presences#2327] opened 2020-10-14 00:40 UTC
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** aidan!#0001 

**What's the name of the service?** Soap2Day | https://soap2day.to

**What should the Presence display?** Something like Netflix or Hulu so others can see what you are watching. 

**If possible, please provide a logo for the service (512x512 minimum)**

**Comment by Isa27-0** [comment] 2020-10-14 11:25
URL: https://www.soap2day.la ~~?~~
@aidanhub

**Comment by aidanhub** [comment] 2020-10-14 15:04
That is it.

**Comment by aidanhub** [comment] 2020-10-14 15:05
https://soap2day.to

**Comment by Isa27-0** [comment] 2020-10-15 00:16
> https://soap2day.to

Huh... I think it has more domains, it can probably be for countries or they are secondary

**Comment by aidanhub** [comment] 2020-10-18 03:54
Will you still be able to do it? You can probably do any domain.

**Comment by Isa27-0** [comment] 2020-10-18 13:28
> Will you still be able to do it? You can probably do any domain.

This depends on the developer, it may be that he or she adds new domains over time

**Comment by SlowLife1661** [comment] 2021-05-06 13:20
Duplicate of #2327

**Comment by Isa27-0** [comment] 2021-07-28 15:59
#3842 
Now he can sleep

**Closed** 2021-07-29 02:49 UTC
Labels: presence request
