### ISSUE TITLE
Telia TV | teliatv.ee

### ISSUE THREAD

**Issue by SeMiD** [PreMiD/Presences#5263] opened 2022-01-03 03:06 UTC
### Discussed in https://github.com/PreMiD/Presences/discussions/4786

<div type='discussions-op-text'>

<sup>Originally posted by **MemeZYT** October 20, 2021</sup>
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [x] Is the site locked to a specific country/region?
- [x] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's the name of the service?** Telia TV | teliatv.ee

**What should the Presence display?** It displays, what channel/movie/show do I watch and What channel, if in live. Also it shows show name in live. It's like Sling TV

**If possible, please provide a logo for the service (512x512 minimum)** https://imgur.com/htn4Ija</div>

**Comment by DarkVillager** [comment] 2022-08-17 14:19
Duplicate of #5387

**Comment by smhman** [comment] 2022-09-26 18:52
Hi! Is the presence ready?

**Comment by DarkVillager** [comment] 2023-04-08 16:34
> Duplicate of #5387

@Bas950

**Closed** 2023-04-08 17:08 UTC
Labels: paid service, region restricted, service request
