### ISSUE TITLE
Add watch app | OSN+

### ISSUE THREAD

**Issue by Youniiss** [PreMiD/Presences#7226] opened 2023-03-10 07:58 UTC
### Website name

OSN+

### Website URL

https://osnplus.com/

### Website logo

https://prnt.sc/XEGLWjUlbqN3

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

I hope to add this application because it is very important, such as Apple TV and Netflix

**Comment by DarkVillager** [comment] 2023-04-09 10:16
Duplicate of #6827 @Bas950

**Closed** 2023-04-09 10:18 UTC
Labels: service request
