### ISSUE TITLE
Notion | Notion.so

### ISSUE THREAD

**Issue by Vagabondit** [PreMiD/Presences#3552] opened 2021-04-19 09:49 UTC
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
Vagabond.it#0005
**What's the name of the service?** 
https://notion.so
**What should the Presence display?** 
The Presence should display page names, time spent on said pages, when you're looking at account settings, whether you're writing/customizing a page or just viewing someone else's, etc. 
**If possible, please provide a logo for the service (512x512 minimum)** 
![image](https://user-images.githubusercontent.com/48355895/115216346-b4314100-a104-11eb-87f2-b5942988a14f.png)

**Comment by ririxidev** [comment] 2021-04-19 18:03
Duplicate of #2757

**Closed by ririxidev** 2021-04-19 18:03 UTC
