### ISSUE TITLE
Creating a presence for the rezka.ag website.

### ISSUE THREAD

**Issue by stromblex** [PreMiD/Presences#7828] opened 2023-12-23 12:12 UTC
### Website name

rezka

### Website URL

https://rezka.ag/

### Website logo

https://images.app.goo.gl/ZNrpVwQXMW55XasX9

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

It's a fairly popular and free website for watching movies, TV shows, anime, and other content dubbed in Russian or Ukrainian. It would be nice if Discord showed which movie or anime you're watching, along with the season and episode, playback time, and progress.

**Comment by Isa27-0** [comment] 2023-12-24 14:37
Duplicate of #7224

**Closed** 2023-12-24 16:09 UTC
Labels: service request
