### ISSUE TITLE
osn plus presence

### ISSUE THREAD

**Issue by unavoidabIe** [PreMiD/Presences#7127] opened 2023-01-20 13:17 UTC
### Website name

osn plus

### Website URL

https://osnplus.com/en-ae/

### Website logo

https://play-lh.googleusercontent.com/z1opRfvyuGGsi-LBhL1g9XQQxAWsvLlvWfIFDdyFEWoJFUEIYrDo80BUS-F5JA01zYU

### Prerequisites

- [X] It is a paid service
- [ ] It displays NSFW content
- [x] It is region restricted

### Description

the show im watching,the episode im watching and how long left till the show ends/how far i am into the show. basically like the netflix presence

**Comment by RisingSunLight42** [comment] 2023-01-21 04:34
Duplicate of #6827

**Comment by DarkVillager** [comment] 2023-04-09 10:16
> Duplicate of #6827

@Bas950

**Closed** 2023-04-09 10:18 UTC
Labels: service request
