### ISSUE TITLE
WWE Network - https://watch.wwe.com/

### ISSUE THREAD

**Issue by SFermani1996** [PreMiD/Presences#2633] opened 2020-12-16 05:42 UTC
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [x] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
TheCanadianToast#4288

**What's the name of the service?**  
WWE Network - https://watch.wwe.com/

**What should the Presence display?** 
Video Program Title
Month/Day/Year *(If Applicable, some video program titles do not have dates on them, Example: The Monday Night War WWE Vs WCW, If no date applies on a video program title, Use Season _ Episode _ , followed by the name of the episode title instead.)*
Video Time Remaining

**If possible, please provide a logo for the service (512x512 minimum)** 

![WWENetworkLogo](https://user-images.githubusercontent.com/76088720/102309892-da1cbe00-3f37-11eb-91fd-41d6f396485a.png)

**Comment by ririxidev** [comment] 2020-12-16 18:09
Duplicate of #974

**Closed by ririxidev** 2020-12-16 18:09 UTC
