### ISSUE TITLE
Funimation 

### ISSUE THREAD

**Issue by DanTheManTV** [PreMiD/Presences#5709] opened 2022-02-02 00:01 UTC
### Description

When video is being played, details do not show. Instead it says "Playing Funimation"
only when video is paused it will show details ie: "Playing Funimation One Piece Season 1 Episode 7" this may only be me but the people from discord told me to submit this

### Steps to Reproduce

1. Go to Funimation
2. Start playing a video
3. Check discord status

### Screenshots

![paused](https://user-images.githubusercontent.com/67932370/152071534-64391686-c28d-4c17-b2a7-dde630a77ddd.PNG)
![playing](https://user-images.githubusercontent.com/67932370/152071535-b68fe92f-8a5b-4c65-aec6-6d6499011d97.PNG)

### Expected Behavior

For it to show details like the other presences do

### Actual Behavior

doesn't show details while playing 

### Page URL

https://www.funimation.com/

### Operating System (OS)

Win 10

### Browser

Chrome

### Browser Version

98.0.4758.66

**Comment by Slowlife01** [comment] 2022-02-02 07:08
Duplicate of #5575

**Closed by Slowlife01** 2022-02-02 07:08 UTC
Labels: 🐛 Bug
