### ISSUE TITLE
Watch Cartoons Online | www.wcostream.com

### ISSUE THREAD

**Issue by FirestormDangerDash** [PreMiD/Presences#5682] opened 2022-01-29 02:55 UTC
### Website name

Watch Cartoons Online

### Website URL

https://www.wcostream.com/

### Website logo

https://www.wcostream.com/wp-content/themes/animewp78712/images/logo.gif

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

Title of show and/or episode.

Bonus cookie for how long until the episode is finished is displayed too.

**Comment by kyrie25** [comment] 2022-01-29 12:22
I'll claim this

**Comment by Isa27-0** [comment] 2022-01-31 21:20
Duplicate of #5413

**Closed** 2022-02-01 01:42 UTC
Labels: Service Request
