### ISSUE TITLE
Nimo.TV

### ISSUE THREAD

**Issue by felipelourenco02** [PreMiD/Presences#3458] opened 2021-04-07 14:17 UTC
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** <Lourençinho#2360>

**What's the name of the service?** <www.nimo.tv | Nimo.TV>

**What should the Presence display?** <Stream name / streamer name / live status>

**If possible, please provide a logo for the service (512x512 minimum)**

**Comment by SlowLife1661** [comment] 2021-04-07 16:09
Duplicate of #3419

**Comment by felipelourenco02** [comment] 2021-04-07 17:02
> Duplicate of #3419

what do u mean?

**Comment by EncryptedDev** [comment] 2021-04-07 17:42
> > Duplicate of #3419
> 
> what do u mean?

its already been requested

**Comment by felipelourenco02** [comment] 2021-04-07 17:43
> > > Duplicate of #3419
> > 
> > 
> > what do u mean?
> 
> its already been requested

ah okay

**Closed** 2021-04-08 06:26 UTC
