### ISSUE TITLE
edX presence request

### ISSUE THREAD

**Issue by Negative-tech** [PreMiD/Presences#4106] opened 2021-07-14 13:52 UTC
**Prerequisites and essential questions** 
- [x] Is it a popular site?
Yes
- [x] Is the website older than 2 months? 
Yes
- [ ] Is the site locked to a specific country/region?
I don't think so
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
No
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
 No
- [ ] Are you a donator/patron?
 No
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?
Yes
**What's your Discord username?** 
NegativE#0001
**What's the name of the service?** 
www.edx.orgg
**What should the Presence display?** 

This is a website that offers free courses from universities like Harvard, for example if you are in a course it will show that you are in a course (it will put the name of the course) if you are in the main page it will show that you are in the main page. 
if you are in a course (it will show the name of the course) if you are in the main page it will show that you are in the main page. And this is what this presence would look like, it would also show how long you have been doing a thing for.

**If possible, please provide a logo for the service (512x512 minimum)** 
![edx_logo_icon_171194](https://user-images.githubusercontent.com/82658847/125633827-03fac036-f869-4729-8bec-65e84003ca2c.png)

**Comment by Isa27-0** [comment] 2021-07-14 14:17
Duplicate of #2789

**Closed** 2021-07-15 08:29 UTC
