### ISSUE TITLE
Twitch Integration Issues

### ISSUE THREAD

**Issue by JakeR04** [PreMiD/Presences#2091] opened 2020-09-01 20:03 UTC
Twitch.tv is not showing up in Discord Status
I have Better Twitch TV installed and FrankerFaceZ, I'm not too sure if this could be conflicting with it. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Twitch
2. Open Discord
3. No status is displayed.

**Expected behaviour**
Twitch should display that im browsing, or watching a live or video. 

**Screenshots**
None Available

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge (chromium)
 - Version 85.0.564.41

**Comment by Jorc0** [comment] 2020-09-09 23:23
I had BetterTTV installed with FrankerFaceZ, try to disable it on your browser and enable it again, that solved the same problem

**Comment by kawakami** [comment] 2020-09-10 12:15
It can cause problems if it changes something on site. (player)

**Comment by JakeR04** [comment] 2020-09-11 18:41
I have disabled and reinstalled BTTV and FFZ but it still doesn't work

**Comment by JakeR04** [comment] 2020-09-11 18:41
Every other site works

**Comment by Link8451** [comment] 2020-09-25 05:17
ive narrowed it down to it being FFZ i will try to find the specific option thats causing it

**Comment by igorquintaes** [comment] 2020-10-01 12:09
Idk if these informations will be of any help, but I could able to reproduce it in a pc with a recenlty installed SO, beforely formatted due problems with Microsoft Windows update. I just installed chrome, premid extensions and premid software, no other extension neither app (like BTTV and FFZ)

![image](https://user-images.githubusercontent.com/10831729/94806682-c1831a00-03c4-11eb-906d-dab52a47c064.png)

After installing chrome and premid, i opened Twitch site and it already started throwing errors on console:

![image](https://user-images.githubusercontent.com/10831729/94806583-9698c600-03c4-11eb-9c2e-f4d7d807fbfd.png)

Is is like settings was not correctly loaded:

![image](https://user-images.githubusercontent.com/10831729/94806648-afa17700-03c4-11eb-9a15-784493f52ce0.png)

I tried to compare Twitch presence file with some others presences, thinking to be some sonfiguration mistake but i didn't found any reason for this error. I could also be able to reproduce it yesterday on my work laptop, but after some time, forcing website refreshes and page navigations, with a unknow reason it started to work. Would it be a Premid error, and not a Presence error?

**Comment by Bas950** [comment] 2020-10-01 12:13
> Idk if these informations will be of any help, but I could able to reproduce it in a pc with a recenlty installed SO, beforely formatted due problems with Microsoft Windows update. I just installed chrome, premid extensions and premid software, no other extension neither app (like BTTV and FFZ)
> 
> ![image](https://user-images.githubusercontent.com/10831729/94806682-c1831a00-03c4-11eb-906d-dab52a47c064.png)
> 
> After installing chrome and premid, i opened Twitch site and it already started throwing errors on console:
> 
> ![image](https://user-images.githubusercontent.com/10831729/94806583-9698c600-03c4-11eb-9c2e-f4d7d807fbfd.png)
> 
> Is is like settings was not correctly loaded:
> 
> ![image](https://user-images.githubusercontent.com/10831729/94806648-afa17700-03c4-11eb-9a15-784493f52ce0.png)
> 
> I tried to compare Twitch presence file with some others presences, thinking to be some sonfiguration mistake but i didn't found any reason for this error. I could also be able to reproduce it yesterday on my work laptop, but after some time, forcing website refreshes and page navigations, with a unknow reason it started to work. Would it be a Premid error, and not a Presence error?

https://media.discordapp.net/attachments/607524579874832446/741949735312687124/PresenceSettings.gif
That should fix your issue.

**Comment by igorquintaes** [comment] 2020-10-01 12:37
>https://media.discordapp.net/attachments/607524579874832446/741949735312687124/PresenceSettings.gif
>That should fix your issue.

It works now, even i don't understanding why

**Comment by JakeR04** [comment] 2020-10-04 12:33
> > https://media.discordapp.net/attachments/607524579874832446/741949735312687124/PresenceSettings.gif
> > That should fix your issue.
> 
> It works now, even i don't understanding why

This worked for me as well. That's a really strange glitch. Is that going to be repaired or is this going to be a permanent work-a-round?

**Comment by ririxichan** [comment] 2020-10-04 12:39
That's because we didn't implement one thing that adding settings to localstorage after adding presence. It will be fixed in v3

**Closed** 2020-10-21 21:21 UTC
Labels: bug
