### ISSUE TITLE
SiriusXM | www.siriusxm.com - URL changed

### ISSUE THREAD

**Issue by cj1705** [PreMiD/Presences#8279] opened 2024-04-14 15:45 UTC
### Steps to Reproduce

Install plugin
go to https://www.siriusxm.com/player/home
plugin does not work

### Expected Behavior

Info to be sent to discord

### Actual Behavior

Nothing

### Page URL

https://www.siriusxm.com/player/home

### Screenshots

![image](https://github.com/PreMiD/Presences/assets/58826886/2dca6704-807c-4e90-afe8-de8e305d021d)
![image](https://github.com/PreMiD/Presences/assets/58826886/c8b1948f-7de8-482a-abed-6672e5afe6e0)
![image](https://github.com/PreMiD/Presences/assets/58826886/17116c5a-bbc3-40f5-8e27-e08bc42d436a)

### Operating System

Windows 11 23H2

### Browser and Version

Firefox 124.0.2 x64

**Comment by tag27** [comment] 2024-04-15 01:36
Duplicate of #8055

**Comment by cj1705** [comment] 2024-04-16 00:09
Oh.. my bad I thought I did check if it already exists as an issue.

**Closed** 2024-04-16 19:24 UTC
Labels: bug
