### ISSUE TITLE
PeacockTV | www.peacocktv.com

### ISSUE THREAD

**Issue by SirDread** [PreMiD/Presences#5209] opened 2021-12-31 23:49 UTC
### Description

The presence does not display the movie's name or time left. It instead shows the description of the movie when the movie is playing. I haven't tried everything else but the user who created the presence can do that, test everything else to make sure it's working before they release an update for it. 

### Steps to Reproduce

1. Add the "PeacockTV" presence from the premid store
2. Go to the website and click any movie
3. Check your discord profile and observe 

### Expected Behavior

I expected the presence to show the movie's name and time left of the movie. And, a pause symbol when the movie is paused. 

### Actual Behavior

It did none of that and instead just showed the movies description on my discord profile.

### Page URL

https://www.peacocktv.com/watch/playback/vod/GMO_00000000409041_01/b1721763-d6c3-34a8-92b4-9f2839af1366

### Operating System (OS)

Windows 11

### Browser

Chrome Beta

### Browser Version

Version 97.0.4692.71 (Official Build) beta (64-bit)

**Comment by EncryptedDev** [comment] 2022-01-01 01:15
Duplicate of #4979

**Closed by EncryptedDev** 2022-01-01 01:15 UTC
Labels: 🐛 Bug
