### ISSUE TITLE
Service Name | Service URL

### ISSUE THREAD

**Issue by Tanishk7988** [PreMiD/Presences#7652] opened 2023-10-06 12:11 UTC
### Steps to Reproduce

https://www.youtube.com/ 
after opening the page click on any video and the presence status will not show 

### Expected Behavior

i thought thata it will show the presence on discord 

### Actual Behavior

it did not worked

### Page URL

https://www.youtube.com/

### Operating System

windows 11

### Browser and Version

google chrome  and latest version

**Comment by DarkVillager** [comment] 2023-10-08 10:49
Youtube | Youtube.com

**Comment by theusaf** [comment] 2023-10-08 18:04
Duplicate of #6370

**Closed by theusaf** 2023-10-08 18:04 UTC
Labels: bug, needs repro
