### ISSUE TITLE
BFlix movie site 

### ISSUE THREAD

**Issue by NiteXXX** [PreMiD/Presences#7535] opened 2023-07-30 19:37 UTC
### Website name

BFLIX

### Website URL

https://bflix.to

### Website logo

https://www.google.com/url?sa=i&url=https%3A%2F%2Fapkpure.com%2Fbflix-movies-tv-series%2Fcom.bflix.playdiary.watchfreemovies&psig=AOvVaw1p3ZCX6Gzk0-S59fMoABLm&ust=1690832182376000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCOCIyPCWt4ADFQAAAAAdAAAAABAW

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

just what movies are being watched

**Comment by Isa27-0** [comment] 2023-07-31 20:51
Duplicate of #5272

**Closed** 2023-07-31 21:44 UTC
Labels: service request
