### ISSUE TITLE
Make a Presence for Goku.to

### ISSUE THREAD

**Issue by Crayharr** [PreMiD/Presences#7245] opened 2023-03-25 18:52 UTC
### Presence name

Goku.to

### Description

Create a Presence for the website Goku.to to view what you are watching and how much of the movie/tv-series is left

### Additional context

I am using Goku quite a bit to watch stuff and i want to show that i am watching movies/tv-series on goku

**Comment by sweezyio** [comment] 2023-03-31 20:22
Duplicate of #7182

**Closed** 2023-05-21 17:25 UTC
Labels: service request
