### ISSUE TITLE
Add Fite.tv

### ISSUE THREAD

**Issue by TheBaconSpace** [PreMiD/Presences#7079] opened 2022-12-19 22:24 UTC
### Website name

Fite.tv

### Website URL

https://fite.tv/ 

### Website logo

https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/FITE_TV.svg/2560px-FITE_TV.svg.png

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

would like to see https://www.fite.tv/p/about/ also any plans on having wwe network for canada and uk presence since canada and uk dont have peacock

**Comment by sweezyio** [comment] 2023-02-28 03:15
Duplicate of #7038.

**Closed** 2023-05-21 17:10 UTC
Labels: service request
