### ISSUE TITLE
I wanted a new presence for a famous manga site 

### ISSUE THREAD

**Issue by ChillSenseii** [PreMiD/Presences#4105] opened 2021-07-14 09:00 UTC
**Prerequisites and essential questions** 
- [X] Is it a popular site?
- [X] Is the website older than 2 months? 
- [x] Is the site locked to a specific country/region?
- [No ] Is the site a paid service? (e.g. Netflix, Hulu)
- [No ] Does the website feature NSFW content? (e.g. porn, etc...)
- [No] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?**  Chill Senseii #6104

**What's the name of the service?**  https://mangasee123.com/

**What should the Presence display?**  The manga I am reading, and an option for the viewer to read it

**If possible, please provide a logo for the service (512x512 minimum)**  https://mangasee123.com/media/navbar.brand.png

**Comment by Isa27-0** [comment] 2021-07-14 13:32
Duplicate of #3404

**Closed** 2021-07-14 13:33 UTC
