### ISSUE TITLE
Nimo TV presence

### ISSUE THREAD

**Issue by zLuker** [PreMiD/Presences#5700] opened 2022-01-31 23:45 UTC
### Website name

Nimo TV

### Website URL

https://www.nimo.tv

### Website logo

https://server-avatar.nimostatic.tv/1599514834540/202104061617693261163_1599514834540_avatar.png

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

the streamer I'm watching. twitch.tv presence model 😀🌸

**Comment by Slowlife01** [comment] 2022-02-02 06:56
Duplicate of #5352

**Closed by Slowlife01** 2022-02-02 06:56 UTC
Labels: Service Request
