### ISSUE TITLE
Khan Academy | www.khanacademy.org - Site doesn't seem to show that you're viewing a lesson, only other pages

### ISSUE THREAD

**Issue by AMufInABox** [PreMiD/Presences#8773] opened 2024-09-30 20:55 UTC
### Steps to Reproduce

1. Go to any lesson such as [here](https://www.khanacademy.org/test-prep/sat-reading-and-writing/x0d47bcec73eb6c4b:foundations-information-and-ideas/x0d47bcec73eb6c4b:command-of-evidence-textual/a/command-of-evidence-textual-lesson) 
2. Status would hang and would spam with console errors 
![image](https://github.com/user-attachments/assets/e80ba5c0-9d0d-4d8e-ac6b-0bac342be5bc)

### Expected Behavior

For the status to show what lesson I'm on

### Actual Behavior

Console spammed with errors

### Page URL

https://www.khanacademy.org/test-prep/sat-reading-and-writing/x0d47bcec73eb6c4b:foundations-information-and-ideas/x0d47bcec73eb6c4b:command-of-evidence-textual/a/command-of-evidence-textual-lesson

### Screenshots

![image](https://github.com/user-attachments/assets/b9158440-3c47-4f65-bae5-4e947171b821)

### Operating System

Windows 11

### Browser and Version

Brave Browser | v 1.70.119

### Additional Comments

It seems to work fine if I go to my homepage or settings, but any page showcasing a lesson or such would cause the status to hang
![image](https://github.com/user-attachments/assets/cedb7b21-be36-49c4-ab2a-228e3905e4a5)

**Comment by tag27** [comment] 2024-10-01 10:32
Duplicate of #7273

**Closed** 2024-10-04 23:44 UTC
Labels: bug
