### ISSUE TITLE
My DisneyPlus Presence is not updating

### ISSUE THREAD

**Issue by msmidnightrain** [PreMiD/Presences#7057] opened 2022-12-06 05:26 UTC
### Steps to Reproduce

It just says on my discord status that I'm browsing, when I am already viewing a movie or a series

### Expected Behavior

It is to show the movie or series I'm watching

### Actual Behavior

It's stuck on the Browsing status

### Page URL

.

### Operating System

Windows 11

### Browser and Version

Google Chrome Version 108.0.5359.71

**Comment by theusaf** [comment] 2024-02-15 21:12
Duplicate of #6092

**Closed by theusaf** 2024-02-15 21:12 UTC
Labels: bug, needs repro
