### ISSUE TITLE
https://animesuge.io/

### ISSUE THREAD

**Issue by soru7** [PreMiD/Presences#3405] opened 2021-04-01 16:50 UTC
**Prerequisites and essential questions** 
- [x] Is it a popular site? yes
- [x] Is the website older than 2 months?  yes
- [ ] Is the site locked to a specific country/region? no 
- [ ] Is the site a paid service? (e.g. Netflix, Hulu) no 
- [ ] Does the website feature NSFW content? (e.g. porn, etc...) Yes but u can use an adblocker
- [ ] Are you a donator/patron? no
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority? yes

**What's your Discord username?**   Soru#7257

**What's the name of the service?**  Anime suge

**What should the Presence display?** THe anime ur watching 

**If possible, please provide a logo for the service (512x512 minimum)** 
![image](https://user-images.githubusercontent.com/81769019/113327358-dba4a300-92e8-11eb-8bed-b9380de61529.png)

**Comment by SlowLife1661** [comment] 2021-04-02 15:39
Duplicate of #3368

**Closed** 2021-04-03 03:01 UTC
