### ISSUE TITLE
Viki | www.viki.com - doesn't display episode information

### ISSUE THREAD

**Issue by rukasu2424** [PreMiD/Presences#9005] opened 2024-12-25 16:23 UTC
### Steps to Reproduce

After this last update, the information of the dramas and episodes does not appear in Presence, only shows the Home screen, profile and collections.

that is, the most important thing is no longer working.

### Expected Behavior

that would work

### Actual Behavior

Doesn't work

### Page URL

https://www.viki.com/

### Operating System

windows 11

### Browser and Version

edge last version

**Comment by theusaf** [comment] 2024-12-26 00:05
Duplicate of #7368

**Closed by theusaf** 2024-12-26 00:05 UTC
Labels: bug, needs repro
