### ISSUE TITLE
Geforce Now for Web | play.geforcenow.com 

### ISSUE THREAD

**Issue by Gummy005** [PreMiD/Presences#3472] opened 2021-04-09 00:09 UTC
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [x] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

Discord: Gummy#5613

Website: play.geforcenow.com | Geforce NOW  

It should have the game you are playing and a timer 

Logo: ![gfn](https://user-images.githubusercontent.com/56605087/114110710-d810ad80-98e0-11eb-90f9-5d1c1f7cea16.png)

**Comment by SlowLife1661** [comment] 2021-04-09 00:29
#1982

**Comment by ririxidev** [comment] 2021-04-09 15:32
Duplicate of #1982

**Closed by ririxidev** 2021-04-09 15:32 UTC
