### ISSUE TITLE
keybr

### ISSUE THREAD

**Issue by daintycook** [PreMiD/Presences#8313] opened 2024-04-27 09:26 UTC
### Website name

keybr

### Website URL

https://www.keybr.com/

### Website logo

https://www.keybr.com/cover.png

### Prerequisites

- [ ] It is a paid service
- [ ] It is region restricted

### Description

This web application will help you to learn touch typing, which means typing through muscle memory without using your eyesight to find the keys on the keyboard. It can improve your typing speed and accuracy dramatically. The opposite is hunt-and-peck typing, a method of typing in which you look at the keyboard instead of the screen, and use only the index fingers.

**Comment by tag27** [comment] 2024-04-27 13:05
Duplicate of #5377

**Closed** 2024-04-27 17:57 UTC
Labels: service request
