### ISSUE TITLE
studytogether | studytogether.com

### ISSUE THREAD

**Issue by divyanshxd** [PreMiD/Presences#7777] opened 2023-11-29 18:14 UTC
### Website name

studytogether 

### Website URL

studytogether.com

### Website logo

https://photos.app.goo.gl/QN9cTr8nqgHgsiKy5

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

Currently studying in room
number of people in group
time elapsed in room

**Comment by Isa27-0** [comment] 2023-11-29 19:12
Duplicate of #6852

**Closed** 2023-11-29 19:17 UTC
Labels: service request
