### ISSUE TITLE
Crunchyroll | www.crunchyroll.com | v3.0.9 - only shows browsing

### ISSUE THREAD

**Issue by camisama0907** [PreMiD/Presences#8851] opened 2024-10-30 18:09 UTC
### Steps to Reproduce

Go to any anime and click an episode

### Expected Behavior

the prescense to show at least the anime i'm watching

### Actual Behavior

prescense only show "browsing"

### Page URL

https://www.crunchyroll.com/

### Screenshots

![imagen](https://github.com/user-attachments/assets/de87556b-f2d6-4d7f-aad7-768ccfc68e27)

### Operating System

Windows 11

### Browser and Version

Firefox 131.0.3 (64-bit)

**Comment by theusaf** [comment] 2024-10-30 22:58
Duplicate of #7464

**Closed by theusaf** 2024-10-30 22:58 UTC
Labels: bug, needs repro
