### ISSUE TITLE
FlixHQ

### ISSUE THREAD

**Issue by Chxarles** [PreMiD/Presences#7039] opened 2022-11-26 10:24 UTC
### Website name

FlixHQ

### Website URL

https://flixhq.ru/home

### Website logo

https://gyazo.com/932c84456ea4e638954dfb802d81f5f6

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

Watch series online free. You can easily access over 30.000 titles and watch series online for free here. No registration is required. Our content is updated daily with fast streaming servers, great features help you easily use and watch your favorite movies. We're confident flixhq.ru is the best free tv series streaming site in the space that you can't simply miss!

**Comment by theusaf** [comment] 2023-05-21 17:11
Duplicate of #6258

**Closed by theusaf** 2023-05-21 17:11 UTC
Labels: service request
