### ISSUE TITLE
Blackboard

### ISSUE THREAD

**Issue by ItsActuallyTJ** [PreMiD/Presences#5763] opened 2022-02-09 22:58 UTC
### Website name

Blackboard

### Website URL

https://bb.csueastbay.edu/

### Website logo

https://play-lh.googleusercontent.com/nsl41ee9htK1fhmr2o3GSA4ipHnEQXCd44WIAp04eENyZ5FaOYHK0uV2oM9HSHGunQ

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

Blackboard Learn is a web-based virtual learning environment and learning management system developed by Blackboard Inc.

**Comment by Isa27-0** [comment] 2022-02-10 00:52
Duplicate of #5441

**Comment by Kaisarion** [comment] 2022-02-11 21:43
This is rather restricted to Blackboard students only as it is not a service easily able to register for. In addition, blackboard websites may be linked to universities which will require constant update to the metadata. Personal opinion, I don't see this happening for near future

**Comment by Isa27-0** [comment] 2022-02-11 21:54
> This is rather restricted to Blackboard students only as it is not a service easily able to register for. In addition, blackboard websites may be linked to universities which will require constant update to the metadata. Personal opinion, I don't see this happening for near future

Well then it's better to close this Issue and the #5441?

**Comment by Kaisarion** [comment] 2022-02-11 23:46
> > This is rather restricted to Blackboard students only as it is not a service easily able to register for. In addition, blackboard websites may be linked to universities which will require constant update to the metadata. Personal opinion, I don't see this happening for near future
> 
> 
> 
> Well then it's better to close this Issue and the #5441?
> 
> 

Correct.

**Comment by Slowlife01** [comment] 2022-02-14 09:25
Duplicate of #5441

**Closed by Slowlife01** 2022-02-14 09:25 UTC
Labels: Service Request
