### ISSUE TITLE
HBO Max |Presence | Bug

### ISSUE THREAD

**Issue by 4vnzu** [PreMiD/Presences#3787] opened 2021-05-21 19:34 UTC
Hello I use PreMiD a lot on discord. I have HBO Max and I wanted to use the HBO Max status. But whenever I use the status instead of showing the movies name or show or how much of the movie is left it just says "Feature". I was wondering if the PreMiD team would fix this issue. Please and thank you!

1. Show the Movie or TV shows name.
2. Show how much of the TV show/ movie is left.
3. Sometimes the pause/play button is broken.

Environment         : Windows 8,10
                              :Browser Chrome

**Comment by ririxidev** [comment] 2021-05-21 19:52
Duplicate of #3428

**Closed by ririxidev** 2021-05-21 19:52 UTC
