### ISSUE TITLE
"Niconico" isn't working

### ISSUE THREAD

**Issue by sgoleo2021** [PreMiD/Presences#7949] opened 2024-01-16 11:51 UTC
### Steps to Reproduce

1. Add "Niconico" to PreMiD
2. open niconico
3. start a video
4. check state in discord

### Expected Behavior

niconico show at state

### Actual Behavior

nothings is showing there

### Page URL

https://www.nicovideo.jp/watch/sm41606052

### Operating System

macos14.2

### Browser and Version

Chrome120.0.6099.109(mac)(arm64)

**Comment by Isa27-0** [comment] 2024-01-16 12:02
Duplicate of #7194

**Closed** 2024-01-16 16:58 UTC
Labels: bug, needs repro
