### ISSUE TITLE
Apple Music and Apple TV+ Presence on PreMiD

### ISSUE THREAD

**Issue by Kuroiyukix** [PreMiD/Presences#5120] opened 2021-12-25 10:50 UTC
### Description

Both the Apple Music and Apple TV+ Presence on PreMiD don't work anymore as the activity doesn't appear on Discord

### Steps to Reproduce

1.Make sure PreMiD is launched and is running in the background

2.On your browser, make sure that the PreMiD extension is installed and you have Apple Music Presence and Apple TV+ Presence downloaded and installed 

3.Make sure Discord is running, open the window and make sure that your status is either Online, Idle or Do not disturb in order to have your activity appear 

4.You need to have an Apple Music and/or Apple TV+ subscription to login to https://music.apple.com/us/browse and https://tv.apple.com on your Desktop/Laptop PC browser

5.Play either a song on Apple Music or an episode/film on Apple TV+ and then open the Discord window and observe if your activity is displayed 

### Screenshots

![image](https://user-images.githubusercontent.com/96650599/147383173-0a2efc22-45ea-4f43-bd0d-88acd3743b55.png)
![image](https://user-images.githubusercontent.com/96650599/147383187-7e25557b-599a-4a7c-b56d-a893f87ed930.png)

### Expected Behavior

Discord activity is supposed to be showing what song I'm listening to or what episode I'm watching.

### Actual Behavior

Discord activity displays nothing

### Page URL

 https://music.apple.com/us/browse https://tv.apple.com

### Operating System (OS)

Windows 11

### Browser

Opera GX

### Browser Version

82.0.4227.50

**Comment by EncryptedDev** [comment] 2021-12-25 14:52
@down-bad, you did the last change on Apple Music, can you confirm this is **not** an issue and is a user-side issue

**Comment by EncryptedDev** [comment] 2021-12-25 14:52
@Kuroiyukix, in future, please use one issue per presence

**Comment by down-bad** [comment] 2021-12-25 18:01
> @down-bad, you did the last change on Apple Music, can you confirm this is **not** an issue and is a user-side issue

Reverting my changes did not solve the issue, so they are not the cause

**Comment by down-bad** [comment] 2021-12-25 18:05
@EncryptedDev seems like #4946 is causing the problem.

**Comment by Slowlife01** [comment] 2021-12-26 06:35
> @EncryptedDev seems like #4946 is causing the problem.

Yes it is. But how did it work for you then

**Comment by Slowlife01** [comment] 2021-12-26 06:36
@Kuroiyukix Apple TV+ seems to be working fine for me

**Comment by down-bad** [comment] 2021-12-26 11:22
> > @EncryptedDev seems like #4946 is causing the problem.
> 
> Yes it is. But how did it work for you then

The pr wasn't merged while I was making the changes

**Comment by Kuroiyukix** [comment] 2021-12-27 02:30
I tried it out again and they're working now so I think both issues have been resolved already. Thank you.

**Closed** 2021-12-27 02:36 UTC
Labels: 🐛 Bug
