### ISSUE TITLE
[Presence | Bug] Monoschinos

### ISSUE THREAD

**Issue by d3kv** [PreMiD/Presences#3398] opened 2021-03-31 18:52 UTC
**Describe the Bug**

Monoschinos presence wont work properly
**Steps to Reproduce**

1.I added the presence from the store
2.Opened the website and it wasnt showing presence on discord( all the other websites show the presence properly)
3.

**Expected Behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/76914071/113195575-b9684200-9262-11eb-9f21-5e05c2dad5af.png)

**Environment**

- OS: w10
- Browser: opera gx
- Version: LVL2 (core: 73.0.3856.421)
  

**Additional context**

Maybe its because the url changed monoschinos.com->monoschinos2.com

**Comment by DarkVillager** [comment] 2021-08-16 09:06
Resolved by #3413
![image](https://user-images.githubusercontent.com/42322979/129539110-8e840de3-53c5-4c0d-92a8-82bb931c583e.png)

**Environment**

- OS: Windows 10
- Browser: Chrome
- Version: 92.0.4515.131 (Official Build) (64-bit) (cohort: Stable)

**Comment by EncryptedDev** [comment] 2021-10-01 23:00
Cannot reproduce, likely to be fixed; reopen if it is still an issue :)

**Closed by EncryptedDev** 2021-10-01 23:00 UTC
Labels: 🐛 Bug
