### ISSUE TITLE
YouTube | youtube.com

### ISSUE THREAD

**Issue by ayyyiieneheuihues** [PreMiD/Presences#7621] opened 2023-09-07 03:48 UTC
### Steps to Reproduce

Go to youtube.com
Play any video
Video should show up in your Discord status but it doesn't.

### Expected Behavior

The presence should show my YouTube activity

### Actual Behavior

It doesn't show anything at all

### Page URL

https://www.youtube.com/watch?v=u5Lv_HXICpo

### Screenshots

![image](https://github.com/PreMiD/Presences/assets/141989026/a1fa2f96-55d4-4cb7-8563-26ca28157d36)
![image](https://github.com/PreMiD/Presences/assets/141989026/d5e6d165-4b4a-4c67-b7de-774d1fba4c33)
![image](https://github.com/PreMiD/Presences/assets/141989026/5c24f906-ee41-421b-8ea1-e2c433adb429)
<img width="226" alt="image" src="https://github.com/PreMiD/Presences/assets/141989026/aff7d8b7-2d51-4a81-94fe-6121c8b6f335">

### Operating System

Windows 11

### Browser and Version

Chrome Version 116.0.5845.142 (Official Build) (64-bit)

### Additional Comments

Hi,

So premid works like 95% of the time with YouTube Music with no problem. I only experience an issue with the actual YouTube presence itself because it doesn't want to show anything (look at the attached screenshots). I can provide any additional info as necessary. A similar issue to this was mentioned in https://github.com/PreMiD/PreMiD/issues/630

**Comment by theusaf** [comment] 2023-09-08 05:01
Duplicate of #6370
This issue is not consistently reproducible so you may want to try some troubleshooting steps listed on the website or in the Discord server's support channel.

**Closed by theusaf** 2023-09-08 05:01 UTC
Labels: bug, needs repro
