### ISSUE TITLE
:Dropout

### ISSUE THREAD

**Issue by xcbbjnxfhj** [PreMiD/Presences#7243] opened 2023-03-24 03:37 UTC
### Website name

:Dropout

### Website URL

https://www.dropout.tv/

### Website logo

https://play-lh.googleusercontent.com/OWxR9M5anSy91z4e90-qdoc2cWywLfOF99F3Erg3bOfFsEDDgHKrnt3Wjd4pOAlaJfzW

### Prerequisites

- [X] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

Would be displaying the show, the season, and the episode name/number with running time left. The same presence as the other streaming service.

**Comment by theusaf** [comment] 2023-05-21 17:25
Duplicate of #6996

**Closed by theusaf** 2023-05-21 17:25 UTC
Labels: service request
