### ISSUE TITLE
Presence for Kocowa+

### ISSUE THREAD

**Issue by Jeno1z** [PreMiD/Presences#7444] opened 2023-06-25 17:05 UTC
### Website name

Kocowa+

### Website URL

https://www.kocowa.com

### Website logo

https://play-lh.googleusercontent.com/JaJtN3R9_DhD9xMWmLqXPsPQ0y3hSnTdiWIetGlARCDjUk7_56TxTuu9H6TP5gLz9Sw

### Prerequisites

- [X] It is a paid service
- [ ] It displays NSFW content
- [x] It is region restricted

### Description

Kocowa is a site where they stream Korean TV shows and movies. It hosts some of the most popular variety shows in Korea, such as Running Man and Home Alone.

**Comment by Isa27-0** [comment] 2023-06-26 01:59
Duplicate of #5750

**Closed** 2023-06-26 13:13 UTC
Labels: service request
