### ISSUE TITLE
New JKanime presence on Discord

### ISSUE THREAD

**Issue by 1Novah** [PreMiD/Presences#8291] opened 2024-04-21 23:03 UTC
### Website name

JKanime

### Website URL

jkanime.net

### Website logo

https://imgur.com/k1KwA4u

### Prerequisites

- [ ] It is a paid service
- [ ] It is region restricted

### Description

I would like the name of the anime to be shown along with the chapter being watched and the time remaining to finish it.

**Comment by tag27** [comment] 2024-04-22 00:51
duplicate of #5259

**Closed** 2024-04-22 16:25 UTC
Labels: service request
