### ISSUE TITLE
Mangafire should be added

### ISSUE THREAD

**Issue by yudoisalwaystaken** [PreMiD/Presences#8008] opened 2024-01-30 21:08 UTC
### Website name

Manga Fire

### Website URL

https://mangafire.to/home

### Website logo

I can't upload an image

### Prerequisites

- [ ] It is a paid service
- [X] It displays NSFW content
- [ ] It is region restricted

### Description

Mangafire is a manga reading site by the same devs of aniwave (previously known as 9anime). And I recommend the site be added to the list of presences.

**Comment by theusaf** [comment] 2024-01-30 23:21
Duplicate of #7417 

This presence already exists. See the linked thread for more info.

**Closed by theusaf** 2024-01-30 23:21 UTC
Labels: service request
