### ISSUE TITLE
SOAP2DAY Presence Request! 🍿

### ISSUE THREAD

**Issue by FreebieII** [PreMiD/Presences#3670] opened 2021-05-06 13:16 UTC
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

Freebie#6865

Soap2day [https://soapgate.org/] They have multiple sub domains, this is to make streaming content faster closer to your location.

Shows what you are watching

![image](https://user-images.githubusercontent.com/69956546/117303902-7dd22080-ae7d-11eb-9898-570928e90a66.png)

**Comment by SlowLife1661** [comment] 2021-05-06 13:20
Duplicate of #2327

**Closed** 2021-05-06 17:13 UTC
