### ISSUE TITLE
Animelon | animelon.com

### ISSUE THREAD

**Issue by frankysetiawan** [PreMiD/Presences#7484] opened 2023-07-13 17:16 UTC
It is currently not working as expected / broken.

### Steps to Reproduce
1. Download PreMid as instructed (Windows + Chrome plugin)
2. Download Animelon presence in Presence Store
3. Tada! It is not working. Whilst YouTube and Netflix presence are working as usual. Closing and reopening browser, Discord, PreMiD, restarting PC was not helping either.

### Environments

- Chrome Version 114.0.5735.110 (Official Build) (32-bit)
- PreMid v2.2.0
- Windows 11
- Discord latest version possible

### Expected Behavior

Animelon is shown in Discord perfectly fine like YouTube and Netflix presence (and other all default presences)

### Actual Behavior

Animelon is not shown in Discord (broken)

### Page URL

https://animelon.com/video/5d3cf9c5a11bb231046310ab
https://animelon.com/video/57986e7c641f6457395b6b22
and all other Animelon videos

### Operating System

Windows 11

### Browser and Version

Chrome Version 114.0.5735.110 (Official Build) (32-bit)

**Comment by DarkVillager** [comment] 2023-07-24 13:03
It works for me
![image](https://github.com/PreMiD/Presences/assets/42322979/54398d4d-0389-4a70-bbd1-766edaf177fc)

**Comment by theusaf** [comment] 2023-08-07 22:55
Closing as cannot reproduce. This may be an issue with troubleshooting or connection with Discord/app/extension and not the presence itself.

**Closed by theusaf** 2023-08-07 22:55 UTC
Labels: bug, needs repro
