### ISSUE TITLE
FlixHQ | flixhq.ru

### ISSUE THREAD

**Issue by ALIENSPECIES394** [PreMiD/Presences#6992] opened 2022-11-12 12:23 UTC
### Website name

FlixHQ

### Website URL

https://flixhq.ru/home

### Website logo

FlixHQ

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

<img width="65" alt="image" src="https://user-images.githubusercontent.com/66906353/201473704-34aa3065-ba65-466a-889b-99dc5c7706ab.png">

**Comment by theusaf** [comment] 2023-05-21 17:11
Duplicate of #6258

**Closed by theusaf** 2023-05-21 17:11 UTC
Labels: service request
