### ISSUE TITLE
[Presence | Bug] YouTube Music

### ISSUE THREAD

**Issue by JustRedTTG** [PreMiD/Presences#4055] opened 2021-07-04 11:09 UTC
**Describe the Bug**
When opening the status menu from discord the time will flash between numbers vigorously for a second at a time

**Steps to Reproduce**
1.play a song on youtube music with more than a minute (example: 1:43)
2.open your status
3.if the glitch occurs the time will flash between numbers vigorously for a second at a time

**Expected Behavior**
countdown the seconds without glitching out

**Screenshots**

**Environment**
- OS: Windows 8.1
- Browser: Chrome
- Version: Version 91.0.4472.124 (Official Build) (64-bit)

**Additional context**
doesn't happen all the time, and seems to happen when there is one minute and any seconds that glitch out between switching

**Comment by DarkVillager** [comment] 2021-08-10 07:04
Can't reproduce.
[![Gif](https://i.gyazo.com/ef4de41e7e1f71b23e1ccb8c287c5e74.gif)](https://gyazo.com/ef4de41e7e1f71b23e1ccb8c287c5e74)

Environment

OS: Windows 10
Browser: Chrome
Version: 92.0.4515.131 (Official Build) (64-bit) (cohort: Stable)

**Comment by EncryptedDev** [comment] 2021-08-30 18:29
Cannot reproduce such issue at the time of writing this, most likely fixed in #4197

**Comment by EncryptedDev** [comment] 2021-10-01 22:43
Resolved in #4695 too

**Closed by EncryptedDev** 2021-10-01 22:43 UTC
Labels: 🐛 Bug
