### ISSUE TITLE
YouTube Music | music.youtube.com

### ISSUE THREAD

**Issue by mihaiofficialRO** [PreMiD/Presences#6130] opened 2022-04-25 22:11 UTC
### Description

PreMiD wont show that you listening from youtube music, if the video itself shows from their own music video

### Steps to Reproduce

1. Go to this link: [https://www.youtube.com/watch?v=3y9FCSlfaMk](url)
2. listen that video
3. check the discord activity

### Screenshots

1. https://cdn.discordapp.com/attachments/527675240231206934/968270698688675850/unknown.png
2. https://cdn.discordapp.com/attachments/527675240231206934/968270793173794846/unknown.png

### Expected Behavior

when you play music in a playlist and a song provided by youtube will come up it won't actually show as your discord status no matter what

### Actual Behavior

like if you liked a provided by youtube song when browsing normal youtube and you play it on youtube music it won't show on your status

### Page URL

https://www.youtube.com/watch?v=3y9FCSlfaMk

### Operating System (OS)

Windows 10

### Browser

Brave

### Browser Version

V1.37.116 (Apr 14, 2022)

**Comment by EncryptedDev** [comment] 2022-05-31 11:20
Duplicate of #6093

**Closed by EncryptedDev** 2022-05-31 11:20 UTC
Labels: bug
