### ISSUE TITLE
I needed a  presence for the website mentioned below

### ISSUE THREAD

**Issue by NandanLX** [PreMiD/Presences#7679] opened 2023-10-21 04:38 UTC
### Website name

Goku - Best website to Watch Free Movies Online

### Website URL

goku.sx

### Website logo

https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0w0p_h5_5h88SrgMJPBTA2SKf5IeKt0eGAb5gk4TDAMW4QZAmbGc_HPOcIgA1HKXN8AQ&usqp=CAU

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

Uhh Like the normal websites such as aniwatch , the movie watching , time elapsed if on home scrolling / exploring home kinda thing... 
Thank You in advance ❤️

**Comment by theusaf** [comment] 2023-10-21 16:32
Duplicate of #7182

**Closed by theusaf** 2023-10-21 16:32 UTC
Labels: service request
