### ISSUE TITLE
Kissasian | kissasion.lu - changed their domain from kissasian.li to kissasian.lu 

### ISSUE THREAD

**Issue by jasonnreformado** [PreMiD/Presences#7920] opened 2024-01-07 15:30 UTC
### Website name

Kissasian

### Website URL

https://kissasian.lu

### Website logo

n/a

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

need to change the url

**Comment by Isa27-0** [comment] 2024-01-07 17:50
It seems to be similar to #7718, but I can't really tell if it's a duplicate, because of the difference in domains.

**Comment by theusaf** [comment] 2024-01-07 17:53
It's pretty much the same, I'll update the description of the other one.

Duplicate of #7718

**Closed by theusaf** 2024-01-07 17:53 UTC
Labels: service request
