### ISSUE TITLE
I would like you to add Presence to Store JKanime.net

### ISSUE THREAD

**Issue by ArthurClaus123** [PreMiD/Presences#8128] opened 2024-02-27 10:53 UTC
### Website name

JKanime

### Website URL

https://jkanime.net/

### Website logo

https://cdn.jkanime.net/logo_jk.png

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

We want it to show the Anime our viewers are watching on our website; such as the name of the Anime, the chapter they are watching, elapsed time, our website logo when adding to their Discord profile, the search engine when they are browsing to watch an upcoming Anime.

**Comment by Isa27-0** [comment] 2024-02-28 00:34
Duplicate of #5259

**Comment by DarkVillager** [comment] 2024-03-15 18:22
^ @Bas950

**Comment by Bas950** [comment] 2024-03-15 19:25
> Duplicate of #5259

**Closed by Bas950** 2024-03-15 19:25 UTC
Labels: service request
