### ISSUE TITLE
HBO GO stuck at "Browsing..." instead of displaying shows that I'm watching

### ISSUE THREAD

**Issue by Kazuhira17** [PreMiD/Presences#7125] opened 2023-01-16 21:00 UTC
### Steps to Reproduce

- Open both Discord 
- and Premid app
- open HBO GO on Browser

### Expected Behavior

display the show I'm watching

### Actual Behavior

just showing "browsing"

### Page URL

https://www.hbogoasia.ph/?campaignid=7859195008&keyword=hbo%20streaming&&source=search&medium=gsem&campaign=2019%7cdec%7cph%7csearch%7cawa%7cawa%7ctraffic%7chbogo%7calwayson%7cgsem%7cpros%7cpb%7cex%7cpure_brand&device=c&gclid=Cj0KCQiAiJSeBhCCARIsAHnAzT9Tg8fcYZ7DUpO7sj-yLBH52ZqCKE6ZluKfFTfffO9DT6BAYRLOCP4aAlYFEALw_wcB&gclid=Cj0KCQiAiJSeBhCCARIsAHnAzT9Tg8fcYZ7DUpO7sj-yLBH52ZqCKE6ZluKfFTfffO9DT6BAYRLOCP4aAlYFEALw_wcB&gclsrc=aw.ds

### Operating System

Windows 10

### Browser and Version

Chrome latest

**Comment by RisingSunLight42** [comment] 2023-01-21 14:21
> I'll take it

Unfortunately, I can't surf on the site since it's georestricted :/

**Comment by theusaf** [comment] 2024-12-05 21:25
Duplicate of #5649

**Closed by theusaf** 2024-12-05 21:25 UTC
Labels: bug
