### ISSUE TITLE
Soundcloud | www.soundcloud.com - Only shows "playing soundcloud"

### ISSUE THREAD

**Issue by xchanii** [PreMiD/Presences#8267] opened 2024-04-09 21:27 UTC
### Steps to Reproduce

1. Launch PreMiD and Discord Stable
2. Visit https://soundcloud.com/
3. Play a track

### Expected Behavior

Rich Presence shows Now Playing, as well as time position

### Actual Behavior

Rich presence simply reads "Playing Soundcloud" with no additional info

### Page URL

https://soundcloud.com/

### Screenshots

![image](https://github.com/PreMiD/Presences/assets/133248886/7068276c-9107-4452-809c-c1e02dda4f21)
![image](https://github.com/PreMiD/Presences/assets/133248886/2dae4d1f-439c-4a24-ad98-d679b8cc6b82)

### Operating System

Windows 10

### Browser and Version

Firefox Version 124.0.2 64-bit

**Comment by xchanii** [comment] 2024-04-12 18:00
Yeah, I did. Can't do the toggle thing for Soundcloud as it appears to have no settings
![image](https://github.com/PreMiD/Presences/assets/133248886/b5e2a7c0-3806-4071-b440-365ad5a5ccdb)
Otherwise, can't think of anything else I could do.

**Comment by tag27** [comment] 2024-04-15 01:39
> Yeah, I did. Can't do the toggle thing for Soundcloud as it appears to have no settings
> ![image](https://github.com/PreMiD/Presences/assets/133248886/b5e2a7c0-3806-4071-b440-365ad5a5ccdb)
> Otherwise, can't think of anything else I could do, since I've done all the other options at least once

Remove the presence and add it back to the store.

**Comment by theusaf** [comment] 2024-08-29 17:55
Duplicate of #6430

**Closed by theusaf** 2024-08-29 17:55 UTC
Labels: bug, needs repro
