### ISSUE TITLE
Max

### ISSUE THREAD

**Issue by citrinates** [PreMiD/Presences#8108] opened 2024-02-25 02:02 UTC
### Website name

Max

### Website URL

https://www.max.com/

### Website logo

https://play-lh.googleusercontent.com/VODqBhdZXQIkQlcv_A2nAq1gPNO7fwfDlUO3UZcgcMy6jAVx05CSU-vFuVFsr9gFUuo

### Prerequisites

- [X] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

Episode / Movie name, time playing

**Comment by Isa27-0** [comment] 2024-02-25 03:30
https://premid.app/store/presences/HBO%20Max Presence supports both domains that use the old name (HBO Max) and the new one (Max)

**Comment by theusaf** [comment] 2024-02-25 03:34
Duplicate of #7371

**Closed by theusaf** 2024-02-25 03:34 UTC
Labels: service request
