### ISSUE TITLE
Viz Media | viz.com

### ISSUE THREAD

**Issue by ninjafatguy** [PreMiD/Presences#4213] opened 2021-08-06 02:08 UTC
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [x] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
NinjaFatGuy#0529

**What's the name of the service?** 
https://www.viz.com/ | VIZ Media

**What should the Presence display?** 
The title and current chapter number of the manga you're reading, plus an elapsed time.

**If possible, please provide a logo for the service (512x512 minimum)** 
![VizMedia](https://user-images.githubusercontent.com/18406824/128445036-aab815f3-3e82-480c-84d7-bdf577e06e10.png)

**Comment by Isa27-0** [comment] 2021-08-06 23:06
Duplicate of #1089

**Comment by SlowLife1661** [comment] 2021-08-07 02:55
Hmm, thanks

**Closed by SlowLife1661** 2021-08-07 02:55 UTC
Labels: presence request
