### ISSUE TITLE
kissanime.lol

### ISSUE THREAD

**Issue by kenkit** [PreMiD/Presences#4020] opened 2021-06-29 19:26 UTC
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**🆂🅰🅶🅴#6154** 

**www.kissanime.lol | Kissanime** 

**Actively Playing anime/episode** 

**If possible, please provide a logo for the service (512x512 minimum)** 
![b8bc34e01e0a8f647e01eb9be84a720c_1558425428_l](https://user-images.githubusercontent.com/1732471/123855656-d2979200-d928-11eb-8693-c9b3754e48be.jpg)

**Comment by Isa27-0** [comment] 2021-06-30 11:52
Duplicate of #4016 
But they may put this URL in the other Issue.

**Closed** 2021-06-30 11:54 UTC
