### ISSUE TITLE
Hi i suggest a new website u can add it !

### ISSUE THREAD

**Issue by Anubis365** [PreMiD/Presences#4246] opened 2021-08-14 01:24 UTC
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [x] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?**  Anubis , Predators .#3678

**What's the name of the service?**  https://www.wwe.com/wwenetwork | Wwe Network

**What should the Presence display?**  Wwe Title

**If possible, please provide a logo for the service (512x512 minimum)**  
https://dp6mhagng1yw3.cloudfront.net/entries/10th/c1bcab6f-286f-42b3-a87a-b9c1997ae9b8.jpg

**Comment by Slowlife01** [comment] 2021-08-14 05:37
Duplicate of #972

**Closed** 2021-08-14 05:38 UTC
