### ISSUE TITLE
Channel4 / All4 - channel4.com

### ISSUE THREAD

**Issue by CatPerson-co-uk** [PreMiD/Presences#7302] opened 2023-04-19 18:22 UTC
### Website name

channel4 / all4

### Website URL

https://www.channel4.com/

### Website logo

https://www.channel4.com/favicon.ico

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

Show your watching, timestamp, and browsing if your on home page

**Comment by Isa27-0** [comment] 2023-04-20 21:39
Duplicate of #5447

**Comment by Isa27-0** [comment] 2023-04-28 20:34
@Bas950 Can you close this Issue?

**Closed** 2023-04-28 20:35 UTC
Labels: service request
