### ISSUE TITLE
HIII

### ISSUE THREAD

**Issue by Skylithh** [PreMiD/Presences#8420] opened 2024-05-26 15:10 UTC
### Website name

9anime

### Website URL

https://9animetv.to/

### Website logo

9anime logo ofc

### Prerequisites

- [ ] It is a paid service
- [ ] It is region restricted

### Description

HII PLS ADD 9ANIME!! >.<

**Comment by theusaf** [comment] 2024-05-26 15:16
Duplicate of #8024

**Closed by theusaf** 2024-05-26 15:16 UTC
Labels: service request
