### ISSUE TITLE
AO3 Presence Request

### ISSUE THREAD

**Issue by violaxo** [PreMiD/Presences#3829] opened 2021-05-27 01:17 UTC
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [x (fanfiction site) ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**viola xo#7297** 

**https://archiveofourown.org** 

**If you're on the site, what you're currently reading, if you're writing a story, looking through your library, (similar to Wattpad)** 

**![image](https://user-images.githubusercontent.com/84884878/119750639-be62ff80-be67-11eb-856b-7255908e0d09.png)**

**Comment by ririxidev** [comment] 2021-05-27 15:50
Duplicate of #3536

**Closed by ririxidev** 2021-05-27 15:50 UTC
