### ISSUE TITLE
Youtube

### ISSUE THREAD

**Issue by lolisfun** [PreMiD/Presences#6047] opened 2022-04-08 10:39 UTC
### Description

Youtube shorts are not properly displayed, it just say's "Playing YouTube".

### Steps to Reproduce

1. Go to https://www.youtube.com/
2. Click on shorts.
3. View any short and see your activity on discord.

### Screenshots

![Screenshot 2022-04-08 160407](https://user-images.githubusercontent.com/59463588/162419643-968f876b-e896-49e6-b2a3-5dbbe838d3a6.png)
![Screenshot 2022-04-08 160336](https://user-images.githubusercontent.com/59463588/162419653-faa9ef83-715e-47cc-92d6-e402b2d062b0.png)

### Expected Behavior

The activity to be the same as it is with regular youtube.

### Actual Behavior

It just says playing youtube.

### Page URL

https://www.youtube.com/ (Shorts).

### Operating System (OS)

Windows 11.

### Browser

Brave.

### Browser Version

Version 1.37.111 Chromium: 100.0.4896.79 (Official Build) (64-bit).

**Comment by EncryptedDev** [comment] 2022-04-08 10:53
Duplicate of #6037 and #6042

**Closed by EncryptedDev** 2022-04-08 10:53 UTC
Labels: 🐛 Bug
