### ISSUE TITLE
YouTube Music | music.youtube.com - uncaught extension exception, no presence displayed

### ISSUE THREAD

**Issue by 2004seraph** [PreMiD/Presences#8207] opened 2024-03-27 15:25 UTC
### Steps to Reproduce

Even after restarting my browser and PC this issue persists.

1. Go to YouTube Music homepage.
2. Play any song, whether it be in a playlist or not.
3. The extension will throw an exception shortly after playback commences and not function again.
4. Trying to play other songs will throw the same exception.

### Expected Behavior

Presence to display in discord

### Actual Behavior

No presence, uncaught extension exception

### Page URL

https://music.youtube.com/watch?v=pZBHKI9mXSk&list=PLmQDP7alGfyZF4Jad_GFEll44IDpBHOKY

### Screenshots

When loading the page on a song:

![image](https://github.com/PreMiD/Presences/assets/45080494/33b54ac9-3f02-449c-a7c5-e3e83e6d63bb)

Errors:

Occasionally during trials I see this error in a file named `presence.ts` on line 18, column 22. It doesn't seem consistent between refreshes. I also sometimes get it when browsing the homepage and not playing a song:

```
TypeError: document.querySelector(...) is null
```

The consistent error:

```
uncaught exception: TIMEOUT: 8362/t.waitFor/</</<@moz-extension://e8a57a39-57be-4ff9-aaea-eafeffcf5392/js/content.js:2:158886
setTimeout handler*8362/t.waitFor/</<@moz-extension://e8a57a39-57be-4ff9-aaea-eafeffcf5392/js/content.js:2:158848
8362/t.waitFor/<@moz-extension://e8a57a39-57be-4ff9-aaea-eafeffcf5392/js/content.js:2:158817
8362/n</<@moz-extension://e8a57a39-57be-4ff9-aaea-eafeffcf5392/js/content.js:2:158577
8362/n<@moz-extension://e8a57a39-57be-4ff9-aaea-eafeffcf5392/js/content.js:2:158322
8362/t.waitFor@moz-extension://e8a57a39-57be-4ff9-aaea-eafeffcf5392/js/content.js:2:158770
3147/wait/<@moz-extension://e8a57a39-57be-4ff9-aaea-eafeffcf5392/js/content.js:2:318831
3147/o</<@moz-extension://e8a57a39-57be-4ff9-aaea-eafeffcf5392/js/content.js:2:318448
3147/o<@moz-extension://e8a57a39-57be-4ff9-aaea-eafeffcf5392/js/content.js:2:318193
wait@moz-extension://e8a57a39-57be-4ff9-aaea-eafeffcf5392/js/content.js:2:318778
videoIDChange@moz-extension://e8a57a39-57be-4ff9-aaea-eafeffcf5392/js/content.js:2:238115
1446/I/<@moz-extension://e8a57a39-57be-4ff9-aaea-eafeffcf5392/js/content.js:2:166234
s@moz-extension://e8a57a39-57be-4ff9-aaea-eafeffcf5392/js/content.js:2:164409
promise callback*l@moz-extension://e8a57a39-57be-4ff9-aaea-eafeffcf5392/js/content.js:2:164574
1446/o</<@moz-extension://e8a57a39-57be-4ff9-aaea-eafeffcf5392/js/content.js:2:164585
1446/o<@moz-extension://e8a57a39-57be-4ff9-aaea-eafeffcf5392/js/content.js:2:164352
I@moz-extension://e8a57a39-57be-4ff9-aaea-eafeffcf5392/js/content.js:2:165777
1446/t.setupVideoModule/<@moz-extension://e8a57a39-57be-4ff9-aaea-eafeffcf5392/js/content.js:2:169500
promise callback*1446/t.setupVideoModule@moz-extension://e8a57a39-57be-4ff9-aaea-eafeffcf5392/js/content.js:2:169489
8290@moz-extension://e8a57a39-57be-4ff9-aaea-eafeffcf5392/js/content.js:2:237790
n@moz-extension://e8a57a39-57be-4ff9-aaea-eafeffcf5392/js/content.js:2:356840
@moz-extension://e8a57a39-57be-4ff9-aaea-eafeffcf5392/js/content.js:2:356880
@moz-extension://e8a57a39-57be-4ff9-aaea-eafeffcf5392/js/content.js:2:356888
```

### Operating System

Ubuntu 22.04

### Browser and Version

Firefox 123.0.1 (64-bit)

### Additional Comments

Other presences like Soundcloud seem perfectly functional.

I use the [Vencord modded Discord client](https://github.com/Vencord/Vesktop), and use the [arRPC](https://github.com/OpenAsar/arrpc) plugin to make PreMiD work.

**Comment by theusaf** [comment] 2024-04-29 17:06
Duplicate of #7094

**Closed by theusaf** 2024-04-29 17:06 UTC
Labels: bug, needs repro
