### ISSUE TITLE
disney+ just shows as browsing when watching an episode

### ISSUE THREAD

**Issue by andrewgr1234** [PreMiD/Presences#7390] opened 2023-05-29 18:43 UTC
### Steps to Reproduce

1. when browsing show as "Browsing..."
2. when watching a show, show as Watching with time stamp, show name, episode, episode title
3. when the episode is paused show as Paused with show name, episode, episode title and withOUT the timestamp

### Expected Behavior

to show the show, episode im watching like the netflix expention

### Actual Behavior

just shows as "browsing..."

### Page URL

happends on any show 

### Screenshots

![Screenshot 2023-05-29 213657](https://github.com/PreMiD/Presences/assets/85031521/b908a4ed-bacc-4b52-b967-bff4e310749b)

### Operating System

Windows 11 Pro

### Browser and Version

google chrome, 113.0.5672.127

**Comment by theusaf** [comment] 2023-05-29 18:44
Duplicate of #7027

**Closed** 2023-05-29 18:45 UTC
Labels: bug, needs repro
