### ISSUE TITLE
Senpa.io Presense

### ISSUE THREAD

**Issue by MistikSenpa** [PreMiD/Presences#1679] opened 2020-06-02 13:32 UTC
**Prerequisites and essential questions** 
- [x] Is it a popular site? Yes
- [x] Is the website older than 2 months?  Yes 
- [ ] Is the site locked to a specific country/region? No
- [ ] Is the site a paid service? (e.g. Netflix, Hulu) No
- [ ] Does the website feature NSFW content? (e.g. porn, etc...) No
- [ ] Are you a donator/patron? No
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority? Yes 

**What's your Discord username?** 
〖ƝƁƘ〗✧Ṃ!ṨҬ!Ḱ✧#4182

**What's the name of the service?** 
Senpa.io

**What should the Presence display?** 
It should display the server the play is connected to + region. e.g if they are on the overworld server it should say EU Overworld
Also should display player nickname they are using ingame
Also should display how much mass they have.

An example of something similar
https://prnt.sc/ssddj4
**If possible, please provide a logo for the service (512x512 minimum)** 
https://senpa.io/assets/images/logo.png

**Comment by MistikSenpa** [comment] 2020-06-02 13:33
I noticed there is already a premid for the website, so it just needs some updates/bug fixes
https://github.com/PreMiD/Presences/tree/master/websites/S/Senpa.io

**Comment by frozaum** [comment] 2020-06-02 19:47
still, this is considered as a duplicate of an already created presence request (#1144), if you want to report a bug, please select the bug report option, thanks.

**Closed by frozaum** 2020-06-02 19:47 UTC
