### ISSUE TITLE
Technopat Sosyal | www.technopat.net

### ISSUE THREAD

**Issue by hKimera** [PreMiD/Presences#5705] opened 2022-02-01 14:06 UTC
### Website name

Technopat Sosyal

### Website URL

https://www.technopat.net/sosyal/

### Website logo

https://www.technopat.net/sosyal/styles/default/xenforo/technopat-logo.png

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

This URL is main of forum.
You can type "Bir sayfaya bakıyor - Ana Sayfa". It means "Looking a page - Home Page".
When user enter any topic, you can type " <Topic title> <Topic owner's name> <For xx.xx time> ".

If they don't understand anythink from my explanation, they can same of LTT Forum. 
Because this two websites doing same thing.
Someone wants help, forum users helps.

**Comment by tag27** [comment] 2024-06-24 10:53
Duplicate of #5270

**Closed** 2024-07-26 21:15 UTC
Labels: service request
