### ISSUE TITLE
HBO GO | hbogo.ro - only displays browsing

### ISSUE THREAD

**Issue by aubeve** [PreMiD/Presences#8876] opened 2024-11-06 13:15 UTC
### Steps to Reproduce

1. open both Premid and Discord
2. open HBO GO on Browser
3. pick a show / movie

### Expected Behavior

display the show I'm watching

### Actual Behavior

just shows "Browsing..." 

### Page URL

www.hbogo.co.th

### Screenshots

![Screenshot 2024-11-06 201207](https://github.com/user-attachments/assets/66a9317b-2c76-4799-92bb-76b6438b4524)

### Operating System

Windows 11

### Browser and Version

Chrome 130.0.6723.92 / Microsoft Edge 130.0.2849.68

**Comment by theusaf** [comment] 2024-12-05 21:24
Duplicate of #7125

**Closed by theusaf** 2024-12-05 21:24 UTC
Labels: bug, needs repro
