### ISSUE TITLE
Gitpod | gitpod.io

### ISSUE THREAD

**Issue by kr-anurag** [PreMiD/Presences#5514] opened 2022-01-06 08:44 UTC
### Website name

Gitpod

### Website URL

https://gitpod.io/

### Website logo

https://gitpod.io/static/media/gitpod.2cdd910d.svg

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

Add presence for Gitpod, to display what project the user is working on, what file the user is editing, etc

**Comment by Isa27-0** [comment] 2022-01-06 12:50
Duplicate of #5236

**Closed** 2022-01-06 14:49 UTC
Labels: Service Request
