### ISSUE TITLE
[Presence | Bug] VoirAnime

### ISSUE THREAD

**Issue by BigBoss320** [PreMiD/Presences#4129] opened 2021-07-20 16:11 UTC
**Describe the Bug**
 The presence "VoirAnime" don't work at all, when watching or searching animes.

**Steps to Reproduce**

1. Open Browser then search VoirAnime.com.
2. Go to the site
3. Search an anime and play video.

**Expected Behavior**
 When watching an anime or even searching it, the presence show on discord what we do on the site (voiranime.com). (_like YouTube presence_).

**Screenshots**
 
![image](https://user-images.githubusercontent.com/44122706/126360138-670c0c18-d7a7-4827-b043-e891e46a7fda.png)

**Environment**

- OS:  Windows 10
- Browser:  Chrome and Opera GX
- Version:  Respectively _91.0.4472.164 (64 bits)_ and _LVL 3 (core: 77.0.4054.257)_
  

**Additional context**
 It's not the application or the extension because YouTube works perfectly.
![image](https://user-images.githubusercontent.com/44122706/126360926-3217d8fe-3b22-4ba6-8bf0-45e8ef22a108.png)

**Comment by Kozou4ever** [comment] 2021-07-20 17:20
hey 👋! I'm currently working on a remake of the presence so yeah, wait for it 😁

**Comment by BigBoss320** [comment] 2021-07-20 18:16
> hey 👋! I'm currently working on a remake of the presence so yeah, wait for it 😁

Oh so if I understand right, the one who actually exists will be replaced by an other.

**Comment by Isa27-0** [comment] 2021-07-23 23:08
Unfortunately, this issue is a duplicate of #3797

**Comment by BigBoss320** [comment] 2021-07-23 23:22
Oops sorry I didn't saw it

**Closed** 2021-07-25 01:11 UTC
Labels: bug
