### ISSUE TITLE
My netflix status is always on browsing

### ISSUE THREAD

**Issue by joannah0906** [PreMiD/Presences#8722] opened 2024-09-10 12:16 UTC
**Describe the bug**
My netflix status is always on browsing even though i am watching a movie/series. I have tried uninstalling the premid and removing the extension and it still doesnt work.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Opera GX
 - Version 2.6.7

**Comment by theusaf** [comment] 2024-09-11 17:09
Duplicate of #8400

**Closed by theusaf** 2024-09-11 17:09 UTC
