### ISSUE TITLE
add star+

### ISSUE THREAD

**Issue by AddStarplus** [PreMiD/Presences#4401] opened 2021-09-23 14:19 UTC
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [x] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 

**What's the name of the service?** 

**What should the Presence display?** 

**If possible, please provide a logo for the service (512x512 minimum)**

**Comment by EncryptedDev** [comment] 2021-09-23 17:45
@AddStarplus, please fill in the short answer questions after the check box questions.

**Comment by EncryptedDev** [comment] 2021-09-24 22:44
Duplicate of #4406

**Closed by EncryptedDev** 2021-09-24 22:44 UTC
Labels: presence request, paid service
