### ISSUE TITLE
Disney+ | www.disneyplus.com - not displaying correctly

### ISSUE THREAD

**Issue by Rajdeep31** [PreMiD/Presences#8568] opened 2024-07-15 14:26 UTC
### Presence name

Disney+

### Description

Disney+ presence not working it was not displaying properly
![image](https://github.com/user-attachments/assets/c2e18fda-2afc-4784-b08b-7a51d10268b3)

**Comment by theusaf** [comment] 2024-07-19 19:26
Duplicate of #6092

**Closed by theusaf** 2024-07-19 19:26 UTC
Labels: feature request
