### ISSUE TITLE
Please Add an option to Hide the Youtube status when the youtube status is 'Viewing homepage'.

### ISSUE THREAD

**Issue by sowsky** [PreMiD/Presences#8341] opened 2024-04-30 16:39 UTC
### Presence name

youtube

### Description

I suggestion to add an option to hide the YouTube status when the YouTube status is Viewing homepage. When the YouTube status is 'Viewing homepage,' other program(Games, Spotify, etc) statuses are not displayed on Discord. I believe there's no need to display when YouTube status is Viewing homepage. 
![537ef39b01803ab9](https://github.com/PreMiD/Presences/assets/23329630/4dbfe9a1-537a-4e20-8386-d76b87ab771c)

### Alternatives

add an option to hide the YouTube status when the YouTube status is Viewing homepage like Hide pause option.

**Comment by tag27** [comment] 2024-04-30 19:40
Duplicate of #8246

**Closed** 2024-04-30 20:06 UTC
Labels: feature request
