### ISSUE TITLE
Notion - not showing page info

### ISSUE THREAD

**Issue by elijaholmos** [PreMiD/Presences#7349] opened 2023-05-11 02:09 UTC
### Steps to Reproduce

1. Go to any user-created page in notion.so
2. Ensure the Notion presence settings for "Show document name" and "Show page icon" are enabled
3. Observe that the PreMiD presence only shows the Notion logo without and page info

### Expected Behavior

PreMiD should display the info for my currently viewed Notion page

### Actual Behavior

PreMiD displays no presence info for the Notion page aside from the Notion logo

### Page URL

https://elijaho.notion.site/Discord-Security-Documentation-9921de13f71a498091a1a0c1910b20f4

### Screenshots

Page in Notion:
![image](https://github.com/PreMiD/Presences/assets/35435704/1cb346b3-63ec-4667-ab2b-634a8d8d9268)

Discord presence:
![image](https://github.com/PreMiD/Presences/assets/35435704/eb5fafa6-61ce-4074-b7ab-5911519ce395)

### Operating System

Windows 10

### Browser and Version

Brave v1.51.114

### Additional Comments

The presence works for center-viewed subpages, for example:

![image](https://github.com/PreMiD/Presences/assets/35435704/d2eee6f2-4f04-411a-af1a-b8f3e68de363)

Discord presence:
![image](https://github.com/PreMiD/Presences/assets/35435704/720c95d1-0990-487b-b794-ff8089f5c1cf)

**Comment by Isa27-0** [comment] 2023-05-14 15:11
Duplicate of #7220

**Closed** 2023-05-21 17:23 UTC
Labels: bug, needs repro
