### ISSUE TITLE
Netflix | PreMiD Stable

### ISSUE THREAD

**Issue by Zenitae** [PreMiD/Presences#7466] opened 2023-07-04 18:13 UTC
### Steps to Reproduce

1. Navigate to the Netflix site
2. Start watching something

### Expected Behavior

Presence should show what I'm watching.

### Actual Behavior

Doesn't show what I'm watching.

### Page URL

https://www.netflix.com/watch/81581073?trackId=155573558

### Screenshots

![image](https://github.com/PreMiD/Presences/assets/138616681/70bb0ecf-e1c7-43d5-8c6b-4a1ce6bdb027)

### Operating System

Windows 11 Pro (22H2, 22621.1848)

### Browser and Version

Brave v1.52.129 (Chromium 114.0.5735.198)

### Additional Comments

Presence does not work anywhere on the site, even when selecting something to watch. Currently using the stable version of PreMiD, not Beta (hence I've opened a new issue).

**Comment by DarkVillager** [comment] 2023-08-03 12:17
@Timeraa & @Bas950  may have something to do with shortURL not working?

**Comment by theusaf** [comment] 2023-08-08 23:03
Duplicate of #7260

**Closed by theusaf** 2023-08-08 23:03 UTC
Labels: bug
