### ISSUE TITLE
SFlix | sflix.to

### ISSUE THREAD

**Issue by vdw0** [PreMiD/Presences#4405] opened 2021-09-24 16:28 UTC
**Prerequisites and essential questions** 
- [x] Is it a popular site? yes, it is a good alternative to netflix
- [x] Is the website older than 2 months?  yes it is!
- [ ] Is the site locked to a specific country/region? no
- [ ] Is the site a paid service? (e.g. Netflix, Hulu) no, you do not need to pay
- [ ] Does the website feature NSFW content? (e.g. porn, etc...) no
- [ ] Are you a donator/patron? no
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority? yes

**What's your Discord username?** Deepman 🏃#6559 

**What's the name of the service?** SFlix

**What should the Presence display?** what you are watching and how long you have been watching it for (similar to netflix)
![sflix](https://user-images.githubusercontent.com/91338495/134709283-76510ea5-04c3-4414-9352-29c8624a9466.jpg)

**If possible, please provide a logo for the service (512x512 minimum)**

**Comment by EncryptedDev** [comment] 2021-09-24 18:32
Please provide the URL(s) for this service

**Comment by EncryptedDev** [comment] 2021-09-24 22:46
Duplicate of #4303

**Closed by EncryptedDev** 2021-09-24 22:46 UTC
Labels: presence request

**Comment by vdw0** [comment] 2021-09-25 12:14
> Please provide the URL(s) for this service

https://sflix.to/

**Comment by vdw0** [comment] 2021-09-26 16:46
update on this?

**Comment by Slowlife01** [comment] 2021-09-26 16:48
Duplicated request

**Comment by vdw0** [comment] 2021-09-26 18:45
alright!

**Comment by vdw0** [comment] 2021-09-27 18:36
have you reviewed it? really not sure how long it takes to do this kind of stuff, or if you will even do it. can you just give me some info please

**Comment by vdw0** [comment] 2021-09-30 16:53
> Duplicated request

duplicated request?

**Comment by vdw0** [comment] 2021-12-25 18:46
> Duplicated request

have you reviewed the requpest, any update on this?
