### ISSUE TITLE
request to add "sonyliv" as a presence

### ISSUE THREAD

**Issue by ieakami** [PreMiD/Presences#8417] opened 2024-05-25 16:36 UTC
### Website name

sonyliv

### Website URL

sonyliv.com

### Website logo

its just sonyliv with a bit of purple and yellow ish texture.

### Prerequisites

- [ ] It is a paid service
- [ ] It is region restricted

### Description

It's a website like “jiocinema” which is already in premid and its called “sonyliv” I wish for you all to add that please!?
It’s an Indian Website/app Theres a lot of sports streams, series, movies etc! ill be greatly thankful of you all! thank you for reading this.. have a great day!

![fallback_sonyliv_logo](https://github.com/PreMiD/Presences/assets/170820081/1040dc18-85b3-4ddd-983a-06279c4511d2)

**Comment by tag27** [comment] 2024-05-25 23:43
#Duplicate of #5292

**Comment by ieakami** [comment] 2024-05-26 03:26
> Duplicate of #5292

So, do I delete this?

**Closed** 2024-05-26 03:39 UTC
Labels: service request
