### ISSUE TITLE
Bionluk | bionluk.com

### ISSUE THREAD

**Issue by ReXulEc** [PreMiD/Presences#3499] opened 2021-04-11 18:14 UTC
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [X] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

cute rexulec#0 0 0 1 

**bionluk.com** 

**This is a plugin that shows what actions users are doing** 

**https://i.imgur.com/pfS8opX.png**

**Comment by ririxidev** [comment] 2021-04-11 19:03
Duplicate of #3350

**Closed by ririxidev** 2021-04-11 19:03 UTC
