### ISSUE TITLE
Plex | app.plex.tv

### ISSUE THREAD

**Issue by senhan07** [PreMiD/Presences#6433] opened 2022-07-10 08:23 UTC
### Steps to Reproduce

1. Open https://app.plex.tv/
2. Play any tv shows or movies
3. Checking my discord activity and the image not showing up
4. Open DevTools Console then the errors showing up
5. The error number keep increasing when the page still load and stop increasing when the page fully loaded

### Expected Behavior

Not showing an error on the console and the image thumbnail show up on my discord activity

### Actual Behavior

Image thumbnail is not showing up on discord activity, It only shows a broken image icon

### Page URL

https://app.plex.tv/desktop/#!/

### Screenshots

Ignore NAME_NOT_RESOLVED some analytics and tracker got blocked because my DNS filtering
![image](https://user-images.githubusercontent.com/34976706/178136790-5f166017-3759-4514-b294-3324a4f17d08.png)
![image](https://user-images.githubusercontent.com/34976706/178136746-df9768fc-62e5-4c7f-873f-40d9a42f260a.png)
![image](https://user-images.githubusercontent.com/34976706/178136758-1a89fbae-c636-46e7-8c3f-46ac40630013.png)

### Operating System

Windows 10 Version 21H2 (build 19044.1806)

### Browser and Version

Chrome Version 103.0.5060.114 (Official Build) (64-bit)

**Comment by Slowlife01** [comment] 2022-07-11 03:10
Duplicate of #6277

**Comment by RisingSunLight42** [comment] 2022-08-03 09:46
Since #6277 is closed, maybe this one can be closed too? @EncryptedDev

**Closed** 2022-08-03 11:28 UTC
Labels: bug, needs repro
