### ISSUE TITLE
watch.lonelil.com | watch.lonelil.ru - update supported URLs

### ISSUE THREAD

**Issue by prophamoon** [PreMiD/Presences#8208] opened 2024-03-27 15:55 UTC
### Presence name

watch.lonelil.com

### Description

Please change the supported URL from 'watch.lonelil.com' to 'watch.lonelil.ru' because they changed domains some time ago. The URL has changed, but the website's name remains the same.

**Comment by Isa27-0** [comment] 2024-03-28 14:22
Wouldn't that be a duplicate of #8021? Since, if the domain has changed, presence won't work.

**Comment by prophamoon** [comment] 2024-03-28 15:11
> Wouldn't that be a duplicate of #8021? Since, if the domain has changed, presence won't work.

No, because the presence was working for them, it just wasn't showing the movie they were watching, now it just doesn't show at all.

**Comment by Isa27-0** [comment] 2024-03-29 01:19
> > Wouldn't that be a duplicate of #8021? Since, if the domain has changed, presence won't work.
> 
> No, because the presence was working for them, it just wasn't showing the movie they were watching, now it just doesn't show at all.

Ah, okay then

**Comment by prophamoon** [comment] 2024-04-04 03:21
By the way, they also got another domain that is 'https://12131989.xyz' and I think it would be cool to have it supported as well.

**Closed** 2024-04-29 01:44 UTC
Labels: feature request
