### ISSUE TITLE
MangaStream | mangastream.xyz

### ISSUE THREAD

**Issue by SeMiD** [PreMiD/Presences#5366] opened 2022-01-03 04:16 UTC
### Discussed in https://github.com/PreMiD/Presences/discussions/4530

<div type='discussions-op-text'>

<sup>Originally posted by **Stangtang** December  7, 2020</sup>
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [x] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

 

**http://mangastream.xyz** 

**What manga, what chapter, what page, and how long you have been reading.** 

**If possible, please provide a logo for the service (512x512 minimum)
![image](https://user-images.githubusercontent.com/66398825/112058426-946c2480-8b28-11eb-9671-e96bb21580fe.png)
** 
</div>

**Comment by kyrie25** [comment] 2022-01-05 14:46
This is a duplicate of #5361

**Comment by DarkVillager** [comment] 2023-04-08 16:31
Duplicate #5361 @Bas950

**Closed** 2023-04-08 17:08 UTC
Labels: service request
