### ISSUE TITLE
Microsoft Team Extension Bug 

### ISSUE THREAD

**Issue by salvadorgeracao** [PreMiD/Presences#3386] opened 2021-03-30 17:11 UTC
**Describe the Bug**
The Microsoft Teams extension doesn't connect in the web version and in the app version. I tried everything but it doesn't connect.

**Steps to Reproduce**
1. Turn on the extension
2. Open the website or the app
3. See if it is showing on your status (It isn't)

**Expected Behavior**
It was expected that the rich presence of Microsoft Teams was showed on the status.

**Screenshots**
-

**Environment**
- OS: Windows 10
- Browser: Chrome
- Version: The most recent version

**Additional context**
Please fix it! :( I want to show to everyone what I'm doing on Microsoft Teams. My discord tag: Salva#3017

**Comment by ririxidev** [comment] 2021-03-31 08:38
Duplicate of #3261

**Closed by ririxidev** 2021-03-31 08:38 UTC
