### ISSUE TITLE
AnimeHeaven | animeheaven.pro

### ISSUE THREAD

**Issue by KingShady56** [PreMiD/Presences#4389] opened 2021-09-21 13:07 UTC
**Prerequisites and essential questions** 
- [x] Is it a popular site? yes 
- [x] Is the website older than 2 months? yes 
- [ ] Is the site locked to a specific country/region? no
- [ ] Is the site a paid service? (e.g. Netflix, Hulu) no
- [ ] Does the website feature NSFW content? (e.g. porn, etc...) no
- [ ] Are you a donator/patron? no
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority? yes

**What's your Discord username?** King Shady#4052 

**What's the name of the service?** Animeheaven. pro

**What should the Presence display?** animesite 

**If possible, please provide a logo for the service (512x512 minimum)**

**Comment by Slowlife01** [comment] 2021-09-22 03:57
I would assume animeheaven.ru is the real AnimeHeaven?

**Comment by Slowlife01** [comment] 2021-09-22 03:59
I'll just close this as duplicate of #1736

**Closed by Slowlife01** 2021-09-22 03:59 UTC
