### ISSUE TITLE
Nimo TV | nimo.tv

### ISSUE THREAD

**Issue by auliaahmad165** [PreMiD/Presences#5507] opened 2022-01-05 12:51 UTC
### Website name

Nimo TV

### Website URL

https://www.nimo.tv/

### Website logo

https://www.nimo.tv/nms/images/apple-touch-icon.67a0300e238e3718b383b6b3b46fb3b8.png

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

Can you make it like Twitch Presences?

**Comment by Isa27-0** [comment] 2022-01-05 21:23
duplicate of #5352

**Closed** 2022-01-05 21:25 UTC
Labels: Service Request
