### ISSUE TITLE
MyDramaList

### ISSUE THREAD

**Issue by fl34b4g** [PreMiD/Presences#1768] opened 2020-06-16 18:54 UTC
**Prerequisites and essential questions** 
- [x] Is it a popular site? 
- [x] Is the website older than 2 months?  Yes
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 

**What's the name of the service?** 
www.mydramalist.com | MyDramaList
**What should the Presence display?** 
What page ur browsing/viewing. 
**If possible, please provide a logo for the service (512x512 minimum)** 
![unnamed](https://user-images.githubusercontent.com/52077646/84815601-8de9d300-b013-11ea-9751-7ee61d3b4aa6.png)

**Comment by Hans5958** [comment] 2020-06-17 12:38
Duplicate of #824, in progress from #1129.

**Closed** 2020-06-17 20:05 UTC
