### ISSUE TITLE
AnimeSuge | animesuge.io

### ISSUE THREAD

**Issue by ProStarPlayer** [PreMiD/Presences#3782] opened 2021-05-21 04:22 UTC
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
xXDarkWishXx#2395

**What's the name of the service?** 
www.animesuge.io

**What should the Presence display?** 
Same as other anime presences. What we are watching, episode, time elapsed, website name. Thank you.

**If possible, please provide a logo for the service (512x512 minimum)**
I was unable to find the proper minimum size requirement for the logo, but this is the best I could find... thank you!
https://ibb.co/kmnsFKL

**Comment by violaxo** [comment] 2021-05-27 01:20
yesssssss, been looking for this

**Comment by ririxidev** [comment] 2021-05-29 09:54
Duplicate of #3368

**Closed by ririxidev** 2021-05-29 09:54 UTC
Labels: presence request
