### ISSUE TITLE
Technopat Sosyal | www.technopat.net/sosyal/

### ISSUE THREAD

**Issue by smilefate** [PreMiD/Presences#8531] opened 2024-06-23 22:37 UTC
### Website name

Technopat Sosyal

### Website URL

https://www.technopat.net/sosyal/

### Website logo

https://www.technopat.net/wp-content/uploads/2021/05/technopat-kutu-logo-bosluklu-1000p.png

### Prerequisites

- [ ] It is a paid service
- [ ] It is region restricted

### Description

[Technopat](https://www.technopat.net/) is a leading technology news and review page in Turkey. Technopat Sosyal is the forum area of this page. Thousands of people visit Technopat's sosyal network every day.

**Here's what I would like to see added to the Premid display;**
- Browsing the [Social homepage](https://www.technopat.net/sosyal/). (Turkish: Sosyal'de geziyor.)
- Looking in a category. (Turkish: -[category_name](https://i.vgy.me/GpUaB8.png)- kategorisine bakıyor.)
- Looking at a section of a category. (Turkish: -category_name- / -[section_name](https://i.vgy.me/TYRFUw.png)- bölümüne bakıyor.)
- Looking at the [activity feed](https://www.technopat.net/sosyal/etkinlik-akisi/) (Turkish: -[feed_name](https://i.vgy.me/2KAzJf.png)- bölümünde)
- Looking for [questions waiting for answers](https://www.technopat.net/sosyal/ozel-bolumler/cevap-bekleyen-sorular.241/). (Turkish: Cevap Bekleyen Sorulara bakıyor)
- Looking at [blogs](https://www.technopat.net/sosyal/blog/) (Turkish: Blog'lara bakıyor)
- Reading blog entries (Turkish: -[blog_name- / -Blog_author_name](https://i.vgy.me/85MGTg.png)-)
 -> A button named Read Blog (Blog'u Oku)
- Looking at [software](https://www.technopat.net/sosyal/indir/). (Turkish: Yazılımlara bakıyor)
- Looking at a software. (Turkish: -[software_name- (-version_number-) / -viewed_section_name](https://i.vgy.me/zju6t9.png)-)
 -> A button named Browse Software (Yazılıma Gözat)
- A search in Social (Turkish: -search_text- adlı içeriği arıyor)
- Looking at a member's profile. (Turkish: -[member_name](https://i.vgy.me/1eWmO0.png)- adlı üyenin profilinde)
- Looking at a topic (Turkish: -[topic_name- / -category_name or section_name](https://i.vgy.me/NMUEHK.png)-)
 -> A button named Read Topic (Konuyu Oku)

For the developer who will volunteer to do this service, I have added images and page links to some of the requests for a better understanding of the requests. I hope this helps 🤲.

Note: The text in brackets in Turkish indicates how the service will be displayed for the Turkish language.
Note: 2 different requests were created for this service in 2022, but there was no response to both requests. So I wanted to create a new request topic about this service request, sorry if I did something wrong ^-^). ([Request 1](https://github.com/PreMiD/Presences/issues/5270), [Request 2](https://github.com/PreMiD/Presences/issues/5705))

**Comment by tag27** [comment] 2024-06-24 10:47
Duplicate of #5705

**Closed** 2024-07-26 21:15 UTC
Labels: service request
