### ISSUE TITLE
Anime Site

### ISSUE THREAD

**Issue by MrsVNF** [PreMiD/Presences#8354] opened 2024-05-05 19:19 UTC
### Website name

animension.to

### Website URL

https://animension.to/

### Website logo

https://imgur.com/om1jxSP

### Prerequisites

- [ ] It is a paid service
- [ ] It is region restricted

### Description

Hello , i'd like for this site to be added, dont have logo image on me!, i'd like a presence where it shows anime name , title,etc.

Ty!.

**Comment by tag27** [comment] 2024-05-06 20:13
Duplicate of #7286

**Closed** 2024-05-06 20:14 UTC
Labels: service request

**Comment by MrsVNF** [comment] 2024-05-07 21:37
> Duplicate of #7286

Ain't no way dawg , ain't no way , i swwear i didn't know 😭 wthhhhhhh lmao
