### ISSUE TITLE
my facebook presence doesnt work

### ISSUE THREAD

**Issue by ShyShyShy190** [PreMiD/Presences#6157] opened 2022-05-01 15:49 UTC
### Description

my facebook presence doesnt work because of the website its because web.facebook.com instead of www.facebook.com #6147
![image](https://user-images.githubusercontent.com/104606098/166153590-18fd5d5d-613a-45e6-8844-8d1fda1c860b.png)

### Steps to Reproduce

i click www.facebook.com and i directly go into web.facebook.com i think its problem is the country or region

### Screenshots

![image](https://user-images.githubusercontent.com/104606098/166153669-10d5282f-48f3-4ec5-9faf-c601ece2095d.png)

### Expected Behavior

it will displayed in discord while i open my facebook in web 

### Actual Behavior

nothing comes out in the discord when i go to the facebook web 

### Page URL

www.facebook.com 

### Operating System (OS)

windows 10

### Browser

chrome

### Browser Version

latest version in chrome

**Comment by Isa27-0** [comment] 2022-05-02 01:13
I would recommend you edit your previous Issue instead of creating a new one.
Because a duplicate Issue can be closed.

**Comment by DarkVillager** [comment] 2022-05-05 07:41
web.facebook.com redirects me to facebook.com so can't reproduce the issue

**Comment by PhilMinecraft** [comment] 2022-05-15 12:02
> web.facebook.com redirects me to facebook.com so can't reproduce the issue

use VPN, ask it where is he living

**Comment by ImRodry** [comment] 2022-05-31 21:42
As mentioned above, we cannot reproduce this as web.facebook.com redirects to facebook.com, so I'll be closing this

**Closed by ImRodry** 2022-05-31 21:42 UTC
Labels: bug, needs repro
