### ISSUE TITLE
YouTube Video not showing in Discord Rich Presence with Vivaldi (only with YouTube Premium)

### ISSUE THREAD

**Issue by ChaoticHolon** [PreMiD/Presences#8048] opened 2024-01-31 05:43 UTC
**Describe the bug**
YouTube content does not show in Discord via Rich Presence as expected (despite PreMiD seemingly working flawlessly everywhere else). It appears to work as expected if you don't have YouTube Premium.

**To Reproduce**
1. Subscribe to YouTube Premium
2. Play any video on YouTube
3. Notice that while PreMiD is working everywhere else, it does not register the playing video on YouTube (or it does so very intermittently).

**Expected behavior**
The YouTube video currently being watched should should be shown via discord rich presence in Discord.

**Desktop:**
 - OS: Windows 10 Enterprise LTSC (19044.3930 / 21H2)
 - Browser: Vivaldi
 - Version: 6.5.3206.57 (Stable channel) (64-bit)

**Comment by tag27** [comment] 2024-04-19 11:26
Duplicate of #8050

**Closed** 2024-04-19 17:10 UTC
