### ISSUE TITLE
Binge | binge.com.au

### ISSUE THREAD

**Issue by EmeraldALT** [PreMiD/Presences#6711] opened 2022-08-29 08:55 UTC
### Website name

Binge

### Website URL

binge.com.au

### Website logo

Binge

### Prerequisites

- [X] It is a paid service
- [ ] It displays NSFW content
- [X] It is region restricted

### Description

Basically anything like other presences (netflix)

Thanks!

**Comment by Isa27-0** [comment] 2022-09-02 19:09
Duplicate of #5320

**Closed** 2023-05-21 17:28 UTC
Labels: service request
