### ISSUE TITLE
Google Drive | drive.google.com

### ISSUE THREAD

**Issue by Isa27-0** [PreMiD/Presences#5931] opened 2022-03-12 23:32 UTC
### Description

Presence is showing the folder name even with the option turned off.

### Steps to Reproduce

1. Add presence, if you don't have it yet.
2.  If the option to show files names is on, turn it off.
3. Open any available folder in 'My Drive'.
4. Observe.

### Screenshots

![image](https://user-images.githubusercontent.com/68751594/158037748-8f08989c-006e-4abd-b857-955ac8dcdb10.png)
![image](https://user-images.githubusercontent.com/68751594/158037780-55b206d3-b4f2-42cb-9924-7b415aebf220.png)

### Expected Behavior

The option was supposed to have worked.

### Actual Behavior

It, even disabled, shows the name of the folder in presence.

### Page URL

https://drive.google.com/drive/u/1/folders

### Operating System (OS)

Windows 10

### Browser

Microsoft Edge

### Browser Version

99.0.1150.39 (64bits)

**Comment by kyrie25** [comment] 2022-03-13 03:39
This is not a bug because the folder name is meant to be shown regardless of the presence's settings
https://github.com/PreMiD/Presences/blob/afc1c67148cb527d238eedbfa6549023149696a5/websites/G/Google%20Drive/presence.ts#L14-L16
I'd recommend making a Feature Request if you want the presence to hide folder name instead

**Comment by EncryptedDev** [comment] 2022-03-13 09:39
I’ll reassign the tags for this to be a Feature Request instead. Seems silly to me to go through the extra effort of making another issue

**Closed** 2022-03-14 22:08 UTC
Labels: Feature Request
