### ISSUE TITLE
Mahjong Soul | mahjongsoul.game.yo-star.com

### ISSUE THREAD

**Issue by pogood01** [PreMiD/Presences#7736] opened 2023-11-12 12:50 UTC
### Website name

Mahjong Soul

### Website URL

https://mahjongsoul.game.yo-star.com/

### Website logo

https://play-lh.googleusercontent.com/G5DpR7LFYB2XA3g6MPCe6CTHWdagmIysr5VeU1dwQkrfIoFmLuynf3LVodqkWWaJQg

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

A blend of cute, appealing anime girls with classical Japanese Mahjong.

**Comment by Isa27-0** [comment] 2023-11-13 23:21
Duplicate of #5456

**Closed** 2023-11-14 00:07 UTC
Labels: service request
