### ISSUE TITLE
Hbo Max Presence Not showing title

### ISSUE THREAD

**Issue by zacierka** [PreMiD/Presences#4270] opened 2021-08-18 23:31 UTC
**Describe the Bug**

Discord Presence only shows the type "Feature/Episode" rather then actual title (See image)
**Steps to Reproduce**

1. Have Premid running both in browser and in tray
2. Navigate to HBO Max
3. Select featured (Movie, Episode) and play
4. Inspect Presence to see "Feature" or "Episode" without title

**Expected Behavior**

View title in discord presence
**Screenshots**

![Example](https://i.imgur.com/MWP82i1.png)
**Environment**

- OS: Windows 10 Build 19043.1165 
- Browser: Brave (Shield Off)
- Version: Version 1.28.105 Chromium: 92.0.4515.131 
  

**Additional context**

Possible Update to selector 
"#Viewport > div.default > div:nth-child(2) > div > div:nth-child(1) > div:nth-child(3) > div > div:nth-child(3) > div:nth-child(2) > div.default.class4.class3 > div:nth-child(4) > div > div > div > div:nth-child(1) > span > span"

**Comment by Isa27-0** [comment] 2021-08-19 00:16
Duplicate of #3428

**Closed** 2021-08-19 03:23 UTC
