### ISSUE TITLE
Pony Town | pony.town

### ISSUE THREAD

**Issue by FalafelToJa** [PreMiD/Presences#8656] opened 2024-08-13 13:51 UTC
### Website name

Pony Town

### Website URL

https://pony.town

### Website logo

https://i.imgur.com/D4tPKtj.png

### Prerequisites

- [ ] It is a paid service
- [ ] It is region restricted

### Description

Can I add how long you play Pony Town and on which server? And maybe what the name of our pony is

**Comment by tag27** [comment] 2024-08-13 15:56
Duplicate of #5416

**Closed** 2024-08-14 21:39 UTC
Labels: service request
