### ISSUE TITLE
Audiomack

### ISSUE THREAD

**Issue by x37yjn** [PreMiD/Presences#8661] opened 2024-08-18 03:29 UTC
### Website name

Audiomack

### Website URL

https://audiomack.com/

### Website logo

https://yt3.googleusercontent.com/ytc/AIdro_mUSALe-J3_dqdxr3QKYPAEQWOUD82xH_B90dBVf_w_Zw=s900-c-k-c0x00ffffff-no-rj

### Prerequisites

- [ ] It is a paid service
- [ ] It is region restricted

### Description

this website is hella good 

it has lot of audios i cant find on soundcloud/youtube so yeah id appreciate if yall add this

its not paid nor region restricted

**Comment by tag27** [comment] 2024-08-18 13:32
Duplicate of #5349

**Closed** 2024-08-19 00:45 UTC
Labels: service request

**Comment by x37yjn** [comment] 2024-08-19 12:47
atleast let us make customrp and use it for ourselves if its not gonna be
publiished publicly i only use audiomack its free and doesnt have block or
anything come on now

yall have soundcloud and youtube which has blocked music and stuff

**Comment by tag27** [comment] 2024-08-19 23:40
> atleast let us make customrp and use it for ourselves if its not gonna be
> publiished publicly i only use audiomack its free and doesnt have block or
> anything come on now
> 
> yall have soundcloud and youtube which has blocked music and stuff

Your issue was closed because someone else has asked for it before. It doesn't mean that it will never be released, you just have to be patient and wait for someone to do it
