### ISSUE TITLE
Request for gaia online presence

### ISSUE THREAD

**Issue by dizzywan** [PreMiD/Presences#7957] opened 2024-01-18 17:35 UTC
### Website name

Gaia Online

### Website URL

https://www.gaiaonline.com/

### Website logo

https://logowik.com/content/uploads/images/gaia-online-circle-icon8118.jpg

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

Hello, me and my friends often play this web game but get sad that we cant display it as an activity, I really hope it can be added because I really love premid and its services thank you!

**Comment by theusaf** [comment] 2024-01-18 17:36
Duplicate of #5432

**Closed by theusaf** 2024-01-18 17:36 UTC
Labels: service request
