### ISSUE TITLE
Youtube presence status timestamp not showing

### ISSUE THREAD

**Issue by NuggetDev41** [PreMiD/Presences#8663] opened 2024-08-19 19:01 UTC
### Steps to Reproduce

I don't know why it even happens, other people I know who use premid never had that bug

### Expected Behavior

So, every presence status shows a timestamp, I expected the same for the youtube one

### Actual Behavior

But whenever I watch a video on youtube, the title, the channel is shown but not the timestamp

### Page URL

www.youtube.com

### Screenshots

![لقطة الشاشة 2024-08-19 201546](https://github.com/user-attachments/assets/bbd478f2-2014-479a-b685-9dec2828dc7b)

### Operating System

Windows 10

### Browser and Version

Microsoft edge 127.0.2651.105

**Comment by tag27** [comment] 2024-08-19 23:44
The timestamps don't appear because you're using the "watching" status. This is a problem with Discord itself, not with PreMiD or presence. If you want the timestamps back, activate this switch in the extension settings:

https://private-user-images.githubusercontent.com/68751594/340139715-f32a2612-e20b-4632-a781-ebf8ead1e3b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxMTEzMTYsIm5iZiI6MTcyNDExMTAxNiwicGF0aCI6Ii82ODc1MTU5NC8zNDAxMzk3MTUtZjMyYTI2MTItZTIwYi00NjMyLWE3ODEtZWJmOGVhZDFlM2I3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDIzNDMzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4ZjRkMjZmMTBiYjQzYzU0NjUwMWUwOTdhNGIwNTU4MDk1YTM5N2MxZjNiYWY1NjRiZTZkYmJjMTViYTI3N2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZthVDqp_P8Iyksp4Pqv9W0re-rkwUGGqHjTfOOy2WRk

**Comment by NuggetDev41** [comment] 2024-08-20 14:48
> The timestamps don't appear because you're using the "watching" status. This is a problem with Discord itself, not with PreMiD or presence.

Then, can you please tell me how do I get them back? Do I need to do a sort of a change in discord?

**Comment by theusaf** [comment] 2024-08-20 23:06
To get them back, use the "use playing status" setting. This is available in the main extension settings which you can access by pressing your profile icon in the extension popup.

Closing since the issue is unrelated to the presence code.

**Closed by theusaf** 2024-08-20 23:06 UTC
Labels: bug, needs repro
