### ISSUE TITLE
Add discord presence for torn.com

### ISSUE THREAD

**Issue by GoldTec** [PreMiD/Presences#6665] opened 2022-08-15 15:50 UTC
### Website name

Torn

### Website URL

https://www.torn.com

### Website logo

https://www.torn.com

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

**About this browser game:** **Torn**  is a text-based, crime-themed [massively multiplayer online role-playing game. The game was developed by the British developer _Joe Chedburn_ in 2003, and is one of the largest text-based online video games. Even today this game has a large player base, with an average of 40,000 players per day. Torn is a text-based online RPG set in Torn City, a dark, murky underworld where only the sharpest survive. In **Torn City** you can be anyone and do anything. Build your character to infinite strengths and play it your way. It's also available on mobile.

I would really like this website to be added to the PreMID Store with discord rich presence, unfortunately, I don't really know how to do something like that even though I would really like. 

It's logo could be the favicon of the  website itself ( or something simillar to my attachments, including the background cover too, i can give more)
![szawZLm8_400x400](https://user-images.githubusercontent.com/26231489/184665885-2b3aa661-87a9-441f-8344-4c23d827fccf.jpg)
![social](https://user-images.githubusercontent.com/26231489/184665930-b8eb72e2-df87-4ccf-92ef-1a597af3702c.png)
![ProfilePic](https://user-images.githubusercontent.com/26231489/184666081-4a932325-733a-4205-9f9d-7f3fc24e5d42.png)

The discord presence could show the time spent on the page, the game icon, the username and id eg.  GoldTec [2232509] (or alternatively a link to the player's profile) and information provided by the user through a configuration ( such as the faction the user is a member of, level, rank,etc.) or through the API ( the game has available API that can provide a lot of information  even for automation

I am available on discord: GoldTec#7488

**Comment by joerkig** [comment] 2022-08-15 16:32
Duplicate of #5440
Might wanna add this info as a comment to that one

**Closed** 2022-08-15 17:06 UTC
Labels: service request
