### ISSUE TITLE
9anime plugin doesnt work

### ISSUE THREAD

**Issue by krmkcbs** [PreMiD/Presences#2227] opened 2020-09-27 19:03 UTC
**Describe the Bug**

9anime plugin doesnt work.It always shows "searching" when im in the site.I think thats because the site has a different gui now.

**Steps to Reproduce**

1.goto 9anime.to
2.select and watch a anime
3.check your status

**Expected Behavior**

It should say "Watching (name)".

**Screenshots**

**Environment**

- OS: Windows 10
- Browser: Firefox
- Version: 81.0 (64-bit)
  

**Additional context**

**Comment by Alanexei** [comment] 2020-09-27 20:26
Unfortunately, the maintainer for this presence has quit the team and left the server. Updates won't be released anytime soon.

**Comment by fr0r** [comment] 2020-09-27 23:10
duplicate of #2229

**Comment by igummie** [comment] 2020-09-28 16:19
stopped working after new ui change

**Comment by Isa27-0** [comment] 2020-09-29 23:08
Hi, your bug is already being solved (#2253)

**Closed** 2020-10-06 14:31 UTC
Labels: bug, help wanted
