### ISSUE TITLE
FACEIT Watch | www.faceit.com

### ISSUE THREAD

**Issue by Miami-1969** [PreMiD/Presences#8659] opened 2024-08-17 14:36 UTC
### Website name

Watch - FACEIT

### Website URL

https://www.faceit.com/en/watch/live

### Website logo

https://play-lh.googleusercontent.com/4iFS-rI0ImIFZyTwjidPChDOTUGxZqX2sCBLRsf9g_noMIUnH9ywsCmCzSu9vSM9Jg

### Prerequisites

- [ ] It is a paid service
- [ ] It is region restricted

### Description

It would be good if you could see the Points of each Team and the time since the Stream started and of course the title of the stream.

**Comment by theusaf** [comment] 2024-08-17 17:44
Duplicate of #8166

**Closed by theusaf** 2024-08-17 17:44 UTC
Labels: service request
