### ISSUE TITLE
HBO GO | add support for hbogo.co.th

### ISSUE THREAD

**Issue by ihatepapaya** [PreMiD/Presences#6255] opened 2022-05-21 05:08 UTC
### Website name

HBO Go

### Website URL

https://hbogo.co.th/

### Website logo

https://www.bing.com/images/search?view=detailV2&ccid=86OX0%2bIg&id=47103E6342133B770EDE65E2B16C81479B899620&thid=OIP.86OX0-Ig7aSbxaaGOAx9ygHaE7&mediaurl=https%3a%2f%2fcdn.windowsreport.com%2fwp-content%2fuploads%2f2020%2f05%2fHBO-Go-romania.jpg&cdnurl=https%3a%2f%2fth.bing.com%2fth%2fid%2fR.f3a397d3e220eda49bc5a686380c7dca%3frik%3dIJaJm0eBbLHiZQ%26pid%3dImgRaw%26r%3d0&exph=1276&expw=1920&q=hbo+go&simid=608048587824397289&FORM=IRPRST&ck=888FDB04BCF2FFDAEE108DF9A7986E74&selectedIndex=0

### Prerequisites

- [X] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

I want it to display the poster of the movie like Netflix. just add the website to the HBO go presence that it already has. the HBO go presence only have Singapore etc. but I want Thailand, please

**Comment by EncryptedDev** [comment] 2022-10-02 10:01
Duplicate of #6703
Resolved in #6709

**Closed by EncryptedDev** 2022-10-02 10:01 UTC
Labels: paid service, region restricted, feature request
