### ISSUE TITLE
HBO Max Presence

### ISSUE THREAD

**Issue by lildrake41** [PreMiD/Presences#7505] opened 2023-07-21 00:13 UTC
### Steps to Reproduce

Can you add https://www.max.com to the URL's List because when I go on HBO Max the Presence doesnt work because that link is not on the url list 

### Expected Behavior

The Presence to work

### Actual Behavior

It doesnt work

### Page URL

https://www.max.com

### Operating System

Windows 11

### Browser and Version

Chrome

**Comment by theusaf** [comment] 2023-07-21 00:14
Duplicate of #7371

**Closed by theusaf** 2023-07-21 00:14 UTC
Labels: bug, needs repro
