### ISSUE TITLE
Media Player Classic - Home Cinema or Black Edition  (MPC-HC/MPC-BE)

### ISSUE THREAD

**Issue by sitiom** [PreMiD/Presences#6446] opened 2022-07-13 06:05 UTC
### Website name

Media Player Classic - Home Cinema or Black Edition

### Website URL

https://github.com/clsid2/mpc-hc | https://sourceforge.net/projects/mpcbe/

### Website logo

![lmpc-hc](https://cdn.discordapp.com/app-assets/427863248734388224/427868871001899009.png) ![mpc-be](https://cdn.discordapp.com/app-assets/427863248734388224/445761845555625994.png)

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

[MPC-HC](https://mpc-hc.org/) is a free and open-source video and audio player for Windows. Currently in active development in a [fork](https://github.com/clsid2/mpc-hc).
[MPC-BE](https://sourceforge.net/projects/mpcbe/) is a fork of MPC-HC with some additional patches

Rich presence should display similar information to what the VLC rich presence displays: Title of video playing, current time/time remaining of video playing, total time of video playing. Information can be extracted from the [Web Interface](https://github.com/angeloanan/MPC-DiscordRPC#how-to-install).

Example with https://github.com/angeloanan/MPC-DiscordRPC:

![Media Player Classic Home Cinema and Black Edition Rich Presence on Discord small profile](https://i.imgur.com/QAAJZgL.png)

**Comment by Isa27-0** [comment] 2022-07-14 13:59
I believe it would be better to close this Issue and open #1514 again. (Even because, it was requested a long time ago.)

**Comment by sitiom** [comment] 2022-07-14 14:01
> I believe it would be better to close this Issue and open #1514 again. (Even because, it was requested a long time ago.)

Oh, right. I wasn't aware there was an existing issue since it was closed.

**Comment by rollingmoai** [comment] 2022-07-22 04:57
@angeloanan Since you made the rich presence mentioned above, are you interested in creating a PreMiD version of it?

**Comment by theusaf** [comment] 2024-08-29 17:57
Duplicate of #1514

**Closed by theusaf** 2024-08-29 17:57 UTC
Labels: service request
