### ISSUE TITLE
Khan Academy Suggestion 

### ISSUE THREAD

**Issue by Hexalizer** [PreMiD/Presences#3927] opened 2021-06-12 19:36 UTC
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
Hex#3333 (<@413550727571570688>)
**What's the name of the service?** 
www.khanacademy.org
**What should the Presence display?** 
What the user is learning (what course they are currently on, what lesson they are on). 
**If possible, please provide a logo for the service (512x512 minimum)** 
![07AxdIVbQ63OEkJoPgCybXt-19 1594914797 1](https://user-images.githubusercontent.com/80934585/121787385-a505c700-cb7a-11eb-9950-b562d4272217.png)

**Comment by ririxidev** [comment] 2021-06-12 19:53
Duplicate of #751

**Closed by ririxidev** 2021-06-12 19:53 UTC
