### ISSUE TITLE
Mr.Piracy | mrpiracy.site

### ISSUE THREAD

**Issue by sluzy-nos4a2** [PreMiD/Presences#4293] opened 2021-08-23 22:20 UTC
![image](https://user-images.githubusercontent.com/66081804/130526606-7374fef1-371c-4674-815d-47a2a32d3c62.png)
**Prerequisites and essential questions**

- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?
 
**What's your Discord username?** Sluzy#6732

**What's the name of the service?** Mr.Piracy | https://mrpiracy.site/

**What should the Presence display?** What movie/tv show is now playing, something like Netflix.

**If possible, please provide a logo for the service (512x512 minimum)**

**Comment by Isa27-0** [comment] 2021-08-23 22:45
Duplicate of #1615

**Closed** 2021-08-24 03:34 UTC
