### ISSUE TITLE
Prime Video | www.primevideo.com | v2.1.25 - Issue Title

### ISSUE THREAD

**Issue by zona05** [PreMiD/Presences#8667] opened 2024-08-20 10:24 UTC
### Steps to Reproduce

1. Open Prime Video 2. Look at the presence

### Expected Behavior

It should show the Prime Video logo, the information of the movie you are watching and time lapse.

### Actual Behavior

Interrogation symbol, and that's it.

### Page URL

https://www.primevideo.com

### Screenshots

![imagen_2024-08-20_122350800](https://github.com/user-attachments/assets/71186ff7-7314-4d1e-8bd8-8308ce116b7b)

### Operating System

Windows 10

### Browser and Version

Chromium: 126.0.6478.226

**Comment by theusaf** [comment] 2024-08-20 23:04
Duplicate of #6324

**Closed by theusaf** 2024-08-20 23:04 UTC
Labels: bug, needs repro
