### ISSUE TITLE
BATOTO | bato.to

### ISSUE THREAD

**Issue by seatofsacrifice** [PreMiD/Presences#8824] opened 2024-10-20 16:05 UTC
### Website name

BATOTO

### Website URL

https://bato.to/v3x

### Website logo

https://bato.to/public-assets/img/bato-favicon.ico?v1

### Prerequisites

- [ ] It is a paid service
- [ ] It is region restricted

### Description

It's a manga reading site, I'd personally like for it to be similar to other manga site presences like Comick.

**Comment by tag27** [comment] 2024-10-21 21:29
Duplicate of #5687

**Closed** 2024-10-22 01:18 UTC
Labels: service request
