### ISSUE TITLE
Premid doesn't show my activities in HBO MAX

### ISSUE THREAD

**Issue by tanlyfps** [PreMiD/Presences#4017] opened 2021-06-29 17:41 UTC
**Describe the Bug**

**Steps to Reproduce**

1.
2.
3.

**Expected Behavior**

**Screenshots**

**Environment**

- OS: 
- Browser: 
- Version: 
  

**Additional context**

**Comment by ririxidev** [comment] 2021-06-29 17:44
Duplicate of #3428

**Closed by ririxidev** 2021-06-29 17:44 UTC
