### ISSUE TITLE
Netflix PreMiD is not working

### ISSUE THREAD

**Issue by LukyMore** [PreMiD/Presences#4261] opened 2021-08-16 16:58 UTC
**Describe the Bug**
Whenever I start watching any show on Netflix (Good Doctor, Jojo's Bizarre Adventure, The Walking Dead etc.)
It will not show that I am watching anything and I am only "browsing"

**Steps to Reproduce**
1. Premid app is running
2. Go to Netflix and watch any show

**Expected Behavior**
It should show the title of the show and the episode, season and name of the episode

**Screenshots**
https://i.gyazo.com/f48321f222e76ebf6875bce7ab466ca4.png
https://i.gyazo.com/2f10d94c1feb527321e5ee47d9f0ab9a.png

**Environment**
- OS: Windows 10
- Browser: Chrome
- Version:  92.0.4515.131 (64-bit) -->

**Additional context**
Actually nothing I guess, it was working fine like one month ago

**Comment by Slowlife01** [comment] 2021-08-16 17:07
Duplicate of #4228

**Closed** 2021-08-16 17:08 UTC
