### ISSUE TITLE
Songsterr Presence Request

### ISSUE THREAD

**Issue by AlperSal** [PreMiD/Presences#4159] opened 2021-07-28 10:23 UTC
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months?
- [ ] Is the site locked to a specific country/region?
- [There is a premium plan but it is free] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's the name of the service?**
 www.songsterr.com | Songsterr

**What should the Presence display?**
Large Image                          | Songsterr Logo 
Title                                       | Songsterr
Details/Upper Text                | Current Song (aria-label="title") - Song Owner (aria-label="artist")
State/Lower Text                   | Chosen Instrument (aria-label="instrument")
Button                                   | WebPage Link

**If possible, please provide a logo for the service (512x512 minimum)** 
![Songsterr](https://user-images.githubusercontent.com/34231577/127306678-dca739a9-71a1-4a12-b228-5ff3e21e7ae0.png)

**Comment by SlowLife1661** [comment] 2021-07-28 14:59
Duplicate of #2853

**Closed by SlowLife1661** 2021-07-28 14:59 UTC
