### ISSUE TITLE
Script error in Jellyfin presence

### ISSUE THREAD

**Issue by Another-sgart** [PreMiD/Presences#7735] opened 2023-11-10 20:54 UTC
### Steps to Reproduce

1. Open browser console
2. Open Jellyfin instance
3. Scroll to the top of the console. An error should be visible

### Expected Behavior

PreMID shows Jellyfin presence in Discord

### Actual Behavior

PreMID presence fails to load with console error

### Page URL

- Redacted publicly accessable URL (Instance 1)
- Local IP and port (Instance 1)
- Redacted publicly accessable URL (Instance 2)

### Screenshots

![image](https://github.com/PreMiD/Presences/assets/48298099/318810db-c98d-4977-a2bf-c9e838d6c62a)

### Operating System

Windows 11

### Browser and Version

Firefox 119.0.1 (64-bit)

### Additional Comments

I was able to reproduce this issue with two different Jellyfin instances. I assume this error is not related to my setup and will happen with any instance provided.
I didn't want my Jellyfin URL visible here. I can provide it if necessary for reproduction tho.

**Comment by theusaf** [comment] 2023-11-11 02:13
The provided screenshot shows an error related to the extension, rather than the presence. Try troubleshooting steps.

Due to similarities, marking as Duplicate of #7590

**Closed by theusaf** 2023-11-11 02:13 UTC
Labels: bug, needs repro

**Comment by Another-sgart** [comment] 2023-11-11 02:33
The issue only occurs with the Jellyfin presence.  The others work without any errors.
