### ISSUE TITLE
WWE Network | watch.wwe.com

### ISSUE THREAD

**Issue by DaBossRyza** [PreMiD/Presences#2579] opened 2020-12-07 06:15 UTC
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [x] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 

**What's the name of the service?**  https://watch.wwe.com/ |  WWE Network

**What should the Presence display?**  The show you are watching on the site and how long you have been watching it for.

**If possible, please provide a logo for the service (512x512 minimum)**  
![image](https://user-images.githubusercontent.com/75602653/101316018-cc1fcb00-38af-11eb-90c8-356d05b0b932.png)

**Comment by ririxidev** [comment] 2020-12-16 07:16
I just noticed it is duplicate of #974

**Closed by ririxidev** 2020-12-16 07:16 UTC
Labels: presence request
