### ISSUE TITLE
i want audiomack to be added

### ISSUE THREAD

**Issue by ilvmoonie** [PreMiD/Presences#7697] opened 2023-10-24 20:35 UTC
### Website name

audiomack

### Website URL

https://audiomack.com

### Website logo

https://yt3.googleusercontent.com/ytc/AOPolaS2xBnTnypVRTJSW-ZyzpP2Mm1eLakF3nT4jx8g=s900-c-k-c0x00ffffff-no-rj

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

Audiomack is an on-demand music streaming and audio discovery platform that allows artists and creators to upload limitless music and podcasts for listeners through its mobile apps and website.

**Comment by Isa27-0** [comment] 2023-10-24 22:34
Duplicate of #5349

**Closed** 2023-10-25 15:13 UTC
Labels: service request
