### ISSUE TITLE
"Youtube" presence is extremely unstable even after re-installing Pre-Mid multiple times. It does not display 90% of the time. All other presences that I use work fine.

### ISSUE THREAD

**Issue by AyushRocks234** [PreMiD/Presences#7481] opened 2023-07-11 17:23 UTC
### Steps to Reproduce

1. Open www.youtube.com on Chrome.
2. Check if pre-mid is connected or not.
3. If yes, check Discord for youtube presence on activity.
4. For confirmation, check if other presences are working or not.
5. Youtube does not show most of the time although all other presences I have been using do instantly.

### Expected Behavior

Youtube presence is supposed to be shown in discord activity.

### Actual Behavior

It does not work most of the time. 

### Page URL

www.youtube.com

### Operating System

Windows 10

### Browser and Version

Chrome

**Comment by theusaf** [comment] 2023-07-12 08:33
Duplicate of #6370

**Closed by theusaf** 2023-07-12 08:33 UTC
Labels: bug, needs repro
